/*
 * Decompiled with CFR 0.152.
 */
package net.minecraft.state.property;

import net.minecraft.block.enums.Attachment;
import net.minecraft.block.enums.BambooLeaves;
import net.minecraft.block.enums.BedPart;
import net.minecraft.block.enums.BlockFace;
import net.minecraft.block.enums.BlockHalf;
import net.minecraft.block.enums.ChestType;
import net.minecraft.block.enums.ComparatorMode;
import net.minecraft.block.enums.CreakingHeartState;
import net.minecraft.block.enums.DoorHinge;
import net.minecraft.block.enums.DoubleBlockHalf;
import net.minecraft.block.enums.NoteBlockInstrument;
import net.minecraft.block.enums.Orientation;
import net.minecraft.block.enums.PistonType;
import net.minecraft.block.enums.RailShape;
import net.minecraft.block.enums.SculkSensorPhase;
import net.minecraft.block.enums.SlabType;
import net.minecraft.block.enums.StairShape;
import net.minecraft.block.enums.StructureBlockMode;
import net.minecraft.block.enums.TestBlockMode;
import net.minecraft.block.enums.Thickness;
import net.minecraft.block.enums.Tilt;
import net.minecraft.block.enums.TrialSpawnerState;
import net.minecraft.block.enums.VaultState;
import net.minecraft.block.enums.WallShape;
import net.minecraft.block.enums.WireConnection;
import net.minecraft.state.property.BooleanProperty;
import net.minecraft.state.property.EnumProperty;
import net.minecraft.state.property.IntProperty;
import net.minecraft.util.math.Direction;
import net.minecraft.util.math.RotationPropertyHelper;

public class Properties {
    final static public BooleanProperty ATTACHED = BooleanProperty.of("attached");
    final static public BooleanProperty BERRIES = BooleanProperty.of("berries");
    final static public BooleanProperty BLOOM = BooleanProperty.of("bloom");
    final static public BooleanProperty BOTTOM = BooleanProperty.of("bottom");
    final static public BooleanProperty CAN_SUMMON = BooleanProperty.of("can_summon");
    final static public BooleanProperty CONDITIONAL = BooleanProperty.of("conditional");
    final static public BooleanProperty DISARMED = BooleanProperty.of("disarmed");
    final static public BooleanProperty DRAG = BooleanProperty.of("drag");
    final static public BooleanProperty ENABLED = BooleanProperty.of("enabled");
    final static public BooleanProperty EXTENDED = BooleanProperty.of("extended");
    final static public BooleanProperty EYE = BooleanProperty.of("eye");
    final static public BooleanProperty FALLING = BooleanProperty.of("falling");
    final static public BooleanProperty HANGING = BooleanProperty.of("hanging");
    final static public BooleanProperty HAS_BOTTLE_0 = BooleanProperty.of("has_bottle_0");
    final static public BooleanProperty HAS_BOTTLE_1 = BooleanProperty.of("has_bottle_1");
    final static public BooleanProperty HAS_BOTTLE_2 = BooleanProperty.of("has_bottle_2");
    final static public BooleanProperty HAS_RECORD = BooleanProperty.of("has_record");
    final static public BooleanProperty HAS_BOOK = BooleanProperty.of("has_book");
    final static public BooleanProperty INVERTED = BooleanProperty.of("inverted");
    final static public BooleanProperty IN_WALL = BooleanProperty.of("in_wall");
    final static public BooleanProperty LIT = BooleanProperty.of("lit");
    final static public BooleanProperty LOCKED = BooleanProperty.of("locked");
    final static public BooleanProperty NATURAL = BooleanProperty.of("natural");
    final static public BooleanProperty OCCUPIED = BooleanProperty.of("occupied");
    final static public BooleanProperty OPEN = BooleanProperty.of("open");
    final static public BooleanProperty PERSISTENT = BooleanProperty.of("persistent");
    final static public BooleanProperty POWERED = BooleanProperty.of("powered");
    final static public BooleanProperty SHORT = BooleanProperty.of("short");
    final static public BooleanProperty SHRIEKING = BooleanProperty.of("shrieking");
    final static public BooleanProperty SIGNAL_FIRE = BooleanProperty.of("signal_fire");
    final static public BooleanProperty SNOWY = BooleanProperty.of("snowy");
    final static public BooleanProperty TIP = BooleanProperty.of("tip");
    final static public BooleanProperty TRIGGERED = BooleanProperty.of("triggered");
    final static public BooleanProperty UNSTABLE = BooleanProperty.of("unstable");
    final static public BooleanProperty WATERLOGGED = BooleanProperty.of("waterlogged");
    final static public EnumProperty<Direction.Axis> HORIZONTAL_AXIS = EnumProperty.of((String)"axis", Direction.Axis.class, (Enum[])new Direction.Axis[]{Direction.Axis.X, Direction.Axis.Z});
    final static public EnumProperty<Direction.Axis> AXIS = EnumProperty.of("axis", Direction.Axis.class);
    final static public BooleanProperty UP = BooleanProperty.of("up");
    final static public BooleanProperty DOWN = BooleanProperty.of("down");
    final static public BooleanProperty NORTH = BooleanProperty.of("north");
    final static public BooleanProperty EAST = BooleanProperty.of("east");
    final static public BooleanProperty SOUTH = BooleanProperty.of("south");
    final static public BooleanProperty WEST = BooleanProperty.of("west");
    final static public EnumProperty<Direction> FACING = EnumProperty.of((String)"facing", Direction.class, (Enum[])new Direction[]{Direction.NORTH, Direction.EAST, Direction.SOUTH, Direction.WEST, Direction.UP, Direction.DOWN});
    final static public EnumProperty<Direction> HOPPER_FACING = EnumProperty.of("facing", Direction.class, facing -> facing != Direction.UP);
    final static public EnumProperty<Direction> HORIZONTAL_FACING = EnumProperty.of("facing", Direction.class, Direction.Type.HORIZONTAL);
    final static public IntProperty FLOWER_AMOUNT = IntProperty.of("flower_amount", 1, 4);
    final static public IntProperty SEGMENT_AMOUNT = IntProperty.of("segment_amount", 1, 4);
    final static public EnumProperty<Orientation> ORIENTATION = EnumProperty.of("orientation", Orientation.class);
    final static public EnumProperty<BlockFace> BLOCK_FACE = EnumProperty.of("face", BlockFace.class);
    final static public EnumProperty<Attachment> ATTACHMENT = EnumProperty.of("attachment", Attachment.class);
    final static public EnumProperty<WallShape> EAST_WALL_SHAPE = EnumProperty.of("east", WallShape.class);
    final static public EnumProperty<WallShape> NORTH_WALL_SHAPE = EnumProperty.of("north", WallShape.class);
    final static public EnumProperty<WallShape> SOUTH_WALL_SHAPE = EnumProperty.of("south", WallShape.class);
    final static public EnumProperty<WallShape> WEST_WALL_SHAPE = EnumProperty.of("west", WallShape.class);
    final static public EnumProperty<WireConnection> EAST_WIRE_CONNECTION = EnumProperty.of("east", WireConnection.class);
    final static public EnumProperty<WireConnection> NORTH_WIRE_CONNECTION = EnumProperty.of("north", WireConnection.class);
    final static public EnumProperty<WireConnection> SOUTH_WIRE_CONNECTION = EnumProperty.of("south", WireConnection.class);
    final static public EnumProperty<WireConnection> WEST_WIRE_CONNECTION = EnumProperty.of("west", WireConnection.class);
    final static public EnumProperty<DoubleBlockHalf> DOUBLE_BLOCK_HALF = EnumProperty.of("half", DoubleBlockHalf.class);
    final static public EnumProperty<BlockHalf> BLOCK_HALF = EnumProperty.of("half", BlockHalf.class);
    final static public EnumProperty<RailShape> RAIL_SHAPE = EnumProperty.of("shape", RailShape.class);
    final static public EnumProperty<RailShape> STRAIGHT_RAIL_SHAPE = EnumProperty.of("shape", RailShape.class, shape -> shape != RailShape.NORTH_EAST && shape != RailShape.NORTH_WEST && shape != RailShape.SOUTH_EAST && shape != RailShape.SOUTH_WEST);
    final static public int AGE_1_MAX = 1;
    final static public int AGE_2_MAX = 2;
    final static public int AGE_3_MAX = 3;
    final static public int AGE_4_MAX = 4;
    final static public int AGE_5_MAX = 5;
    final static public int AGE_7_MAX = 7;
    final static public int AGE_15_MAX = 15;
    final static public int AGE_25_MAX = 25;
    final static public IntProperty AGE_1 = IntProperty.of("age", 0, 1);
    final static public IntProperty AGE_2 = IntProperty.of("age", 0, 2);
    final static public IntProperty AGE_3 = IntProperty.of("age", 0, 3);
    final static public IntProperty AGE_4 = IntProperty.of("age", 0, 4);
    final static public IntProperty AGE_5 = IntProperty.of("age", 0, 5);
    final static public IntProperty AGE_7 = IntProperty.of("age", 0, 7);
    final static public IntProperty AGE_15 = IntProperty.of("age", 0, 15);
    final static public IntProperty AGE_25 = IntProperty.of("age", 0, 25);
    final static public IntProperty BITES = IntProperty.of("bites", 0, 6);
    final static public IntProperty CANDLES = IntProperty.of("candles", 1, 4);
    final static public IntProperty DELAY = IntProperty.of("delay", 1, 4);
    final static public int DISTANCE_1_7_MAX = 7;
    final static public IntProperty DISTANCE_1_7 = IntProperty.of("distance", 1, 7);
    final static public IntProperty EGGS = IntProperty.of("eggs", 1, 4);
    final static public IntProperty HATCH = IntProperty.of("hatch", 0, 2);
    final static public IntProperty LAYERS = IntProperty.of("layers", 1, 8);
    final static public int LEVEL_8_MIN = 0;
    final static public int LEVEL_1_8_MIN = 1;
    final static public int LEVEL_3_MAX = 3;
    final static public int LEVEL_1_8_MAX = 8;
    final static public IntProperty LEVEL_3 = IntProperty.of("level", 1, 3);
    final static public IntProperty LEVEL_8 = IntProperty.of("level", 0, 8);
    final static public IntProperty LEVEL_1_8 = IntProperty.of("level", 1, 8);
    final static public IntProperty HONEY_LEVEL = IntProperty.of("honey_level", 0, 5);
    final static public int LEVEL_15_MAX = 15;
    final static public IntProperty LEVEL_15 = IntProperty.of("level", 0, 15);
    final static public IntProperty MOISTURE = IntProperty.of("moisture", 0, 7);
    final static public IntProperty NOTE = IntProperty.of("note", 0, 24);
    final static public IntProperty PICKLES = IntProperty.of("pickles", 1, 4);
    final static public IntProperty POWER = IntProperty.of("power", 0, 15);
    final static public IntProperty STAGE = IntProperty.of("stage", 0, 1);
    final static public int DISTANCE_0_7_MAX = 7;
    final static public IntProperty DISTANCE_0_7 = IntProperty.of("distance", 0, 7);
    final static public int CHARGES_MIN = 0;
    final static public int CHARGES_MAX = 4;
    final static public IntProperty CHARGES = IntProperty.of("charges", 0, 4);
    final static public IntProperty HYDRATION = IntProperty.of("hydration", 0, 3);
    final static public IntProperty ROTATION = IntProperty.of("rotation", 0, RotationPropertyHelper.getMax());
    final static public EnumProperty<BedPart> BED_PART = EnumProperty.of("part", BedPart.class);
    final static public EnumProperty<ChestType> CHEST_TYPE = EnumProperty.of("type", ChestType.class);
    final static public EnumProperty<ComparatorMode> COMPARATOR_MODE = EnumProperty.of("mode", ComparatorMode.class);
    final static public EnumProperty<DoorHinge> DOOR_HINGE = EnumProperty.of("hinge", DoorHinge.class);
    final static public EnumProperty<NoteBlockInstrument> INSTRUMENT = EnumProperty.of("instrument", NoteBlockInstrument.class);
    final static public EnumProperty<PistonType> PISTON_TYPE = EnumProperty.of("type", PistonType.class);
    final static public EnumProperty<SlabType> SLAB_TYPE = EnumProperty.of("type", SlabType.class);
    final static public EnumProperty<StairShape> STAIR_SHAPE = EnumProperty.of("shape", StairShape.class);
    final static public EnumProperty<StructureBlockMode> STRUCTURE_BLOCK_MODE = EnumProperty.of("mode", StructureBlockMode.class);
    final static public EnumProperty<BambooLeaves> BAMBOO_LEAVES = EnumProperty.of("leaves", BambooLeaves.class);
    final static public EnumProperty<Tilt> TILT = EnumProperty.of("tilt", Tilt.class);
    final static public EnumProperty<Direction> VERTICAL_DIRECTION = EnumProperty.of((String)"vertical_direction", Direction.class, (Enum[])new Direction[]{Direction.UP, Direction.DOWN});
    final static public EnumProperty<Thickness> THICKNESS = EnumProperty.of("thickness", Thickness.class);
    final static public EnumProperty<SculkSensorPhase> SCULK_SENSOR_PHASE = EnumProperty.of("sculk_sensor_phase", SculkSensorPhase.class);
    final static public BooleanProperty SLOT_0_OCCUPIED = BooleanProperty.of("slot_0_occupied");
    final static public BooleanProperty SLOT_1_OCCUPIED = BooleanProperty.of("slot_1_occupied");
    final static public BooleanProperty SLOT_2_OCCUPIED = BooleanProperty.of("slot_2_occupied");
    final static public BooleanProperty SLOT_3_OCCUPIED = BooleanProperty.of("slot_3_occupied");
    final static public BooleanProperty SLOT_4_OCCUPIED = BooleanProperty.of("slot_4_occupied");
    final static public BooleanProperty SLOT_5_OCCUPIED = BooleanProperty.of("slot_5_occupied");
    final static public IntProperty DUSTED = IntProperty.of("dusted", 0, 3);
    final static public BooleanProperty CRACKED = BooleanProperty.of("cracked");
    final static public BooleanProperty CRAFTING = BooleanProperty.of("crafting");
    final static public EnumProperty<TrialSpawnerState> TRIAL_SPAWNER_STATE = EnumProperty.of("trial_spawner_state", TrialSpawnerState.class);
    final static public EnumProperty<VaultState> VAULT_STATE = EnumProperty.of("vault_state", VaultState.class);
    final static public EnumProperty<CreakingHeartState> CREAKING_HEART_STATE = EnumProperty.of("creaking_heart_state", CreakingHeartState.class);
    final static public BooleanProperty OMINOUS = BooleanProperty.of("ominous");
    final static public EnumProperty<TestBlockMode> TEST_BLOCK_MODE = EnumProperty.of("mode", TestBlockMode.class);
    final static public BooleanProperty MAP = BooleanProperty.of("map");
}

