/*
 * Decompiled with CFR 0.152.
 */
package net.minecraft.network.packet;

import net.minecraft.network.NetworkSide;
import net.minecraft.network.listener.ClientPlayPacketListener;
import net.minecraft.network.listener.ServerPlayPacketListener;
import net.minecraft.network.packet.Packet;
import net.minecraft.network.packet.PacketType;
import net.minecraft.network.packet.c2s.play.AcknowledgeChunksC2SPacket;
import net.minecraft.network.packet.c2s.play.AcknowledgeReconfigurationC2SPacket;
import net.minecraft.network.packet.c2s.play.AdvancementTabC2SPacket;
import net.minecraft.network.packet.c2s.play.BoatPaddleStateC2SPacket;
import net.minecraft.network.packet.c2s.play.BookUpdateC2SPacket;
import net.minecraft.network.packet.c2s.play.BundleItemSelectedC2SPacket;
import net.minecraft.network.packet.c2s.play.ButtonClickC2SPacket;
import net.minecraft.network.packet.c2s.play.ChangeGameModeC2SPacket;
import net.minecraft.network.packet.c2s.play.ChatCommandSignedC2SPacket;
import net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket;
import net.minecraft.network.packet.c2s.play.ClickSlotC2SPacket;
import net.minecraft.network.packet.c2s.play.ClientCommandC2SPacket;
import net.minecraft.network.packet.c2s.play.ClientStatusC2SPacket;
import net.minecraft.network.packet.c2s.play.ClientTickEndC2SPacket;
import net.minecraft.network.packet.c2s.play.CloseHandledScreenC2SPacket;
import net.minecraft.network.packet.c2s.play.CommandExecutionC2SPacket;
import net.minecraft.network.packet.c2s.play.CraftRequestC2SPacket;
import net.minecraft.network.packet.c2s.play.CreativeInventoryActionC2SPacket;
import net.minecraft.network.packet.c2s.play.DebugSampleSubscriptionC2SPacket;
import net.minecraft.network.packet.c2s.play.HandSwingC2SPacket;
import net.minecraft.network.packet.c2s.play.JigsawGeneratingC2SPacket;
import net.minecraft.network.packet.c2s.play.MessageAcknowledgmentC2SPacket;
import net.minecraft.network.packet.c2s.play.PickItemFromBlockC2SPacket;
import net.minecraft.network.packet.c2s.play.PickItemFromEntityC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerInputC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerInteractEntityC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerLoadedC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket;
import net.minecraft.network.packet.c2s.play.QueryBlockNbtC2SPacket;
import net.minecraft.network.packet.c2s.play.QueryEntityNbtC2SPacket;
import net.minecraft.network.packet.c2s.play.RecipeBookDataC2SPacket;
import net.minecraft.network.packet.c2s.play.RecipeCategoryOptionsC2SPacket;
import net.minecraft.network.packet.c2s.play.RenameItemC2SPacket;
import net.minecraft.network.packet.c2s.play.RequestCommandCompletionsC2SPacket;
import net.minecraft.network.packet.c2s.play.SelectMerchantTradeC2SPacket;
import net.minecraft.network.packet.c2s.play.SetTestBlockC2SPacket;
import net.minecraft.network.packet.c2s.play.SlotChangedStateC2SPacket;
import net.minecraft.network.packet.c2s.play.SpectatorTeleportC2SPacket;
import net.minecraft.network.packet.c2s.play.TeleportConfirmC2SPacket;
import net.minecraft.network.packet.c2s.play.TestInstanceBlockActionC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateBeaconC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateCommandBlockC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateCommandBlockMinecartC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateDifficultyC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateDifficultyLockC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateJigsawC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdatePlayerAbilitiesC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateSelectedSlotC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateSignC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateStructureBlockC2SPacket;
import net.minecraft.network.packet.c2s.play.VehicleMoveC2SPacket;
import net.minecraft.network.packet.s2c.play.AdvancementUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.BlockBreakingProgressS2CPacket;
import net.minecraft.network.packet.s2c.play.BlockEntityUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.BlockEventS2CPacket;
import net.minecraft.network.packet.s2c.play.BlockUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.BossBarS2CPacket;
import net.minecraft.network.packet.s2c.play.BundleDelimiterS2CPacket;
import net.minecraft.network.packet.s2c.play.BundleS2CPacket;
import net.minecraft.network.packet.s2c.play.ChatMessageS2CPacket;
import net.minecraft.network.packet.s2c.play.ChatSuggestionsS2CPacket;
import net.minecraft.network.packet.s2c.play.ChunkBiomeDataS2CPacket;
import net.minecraft.network.packet.s2c.play.ChunkDataS2CPacket;
import net.minecraft.network.packet.s2c.play.ChunkDeltaUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.ChunkLoadDistanceS2CPacket;
import net.minecraft.network.packet.s2c.play.ChunkRenderDistanceCenterS2CPacket;
import net.minecraft.network.packet.s2c.play.ChunkSentS2CPacket;
import net.minecraft.network.packet.s2c.play.ClearTitleS2CPacket;
import net.minecraft.network.packet.s2c.play.CloseScreenS2CPacket;
import net.minecraft.network.packet.s2c.play.CommandSuggestionsS2CPacket;
import net.minecraft.network.packet.s2c.play.CommandTreeS2CPacket;
import net.minecraft.network.packet.s2c.play.CooldownUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.CraftFailedResponseS2CPacket;
import net.minecraft.network.packet.s2c.play.DamageTiltS2CPacket;
import net.minecraft.network.packet.s2c.play.DeathMessageS2CPacket;
import net.minecraft.network.packet.s2c.play.DebugSampleS2CPacket;
import net.minecraft.network.packet.s2c.play.DifficultyS2CPacket;
import net.minecraft.network.packet.s2c.play.EndCombatS2CPacket;
import net.minecraft.network.packet.s2c.play.EnterCombatS2CPacket;
import net.minecraft.network.packet.s2c.play.EnterReconfigurationS2CPacket;
import net.minecraft.network.packet.s2c.play.EntitiesDestroyS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityAnimationS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityAttachS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityAttributesS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityDamageS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityEquipmentUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityPassengersSetS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityPositionS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityPositionSyncS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityS2CPacket;
import net.minecraft.network.packet.s2c.play.EntitySetHeadYawS2CPacket;
import net.minecraft.network.packet.s2c.play.EntitySpawnS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityStatusEffectS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityStatusS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityTrackerUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.EntityVelocityUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.ExperienceBarUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.ExplosionS2CPacket;
import net.minecraft.network.packet.s2c.play.GameJoinS2CPacket;
import net.minecraft.network.packet.s2c.play.GameMessageS2CPacket;
import net.minecraft.network.packet.s2c.play.GameStateChangeS2CPacket;
import net.minecraft.network.packet.s2c.play.HealthUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.InventoryS2CPacket;
import net.minecraft.network.packet.s2c.play.ItemPickupAnimationS2CPacket;
import net.minecraft.network.packet.s2c.play.LightUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.LookAtS2CPacket;
import net.minecraft.network.packet.s2c.play.MapUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.MoveMinecartAlongTrackS2CPacket;
import net.minecraft.network.packet.s2c.play.NbtQueryResponseS2CPacket;
import net.minecraft.network.packet.s2c.play.OpenHorseScreenS2CPacket;
import net.minecraft.network.packet.s2c.play.OpenScreenS2CPacket;
import net.minecraft.network.packet.s2c.play.OpenWrittenBookS2CPacket;
import net.minecraft.network.packet.s2c.play.OverlayMessageS2CPacket;
import net.minecraft.network.packet.s2c.play.ParticleS2CPacket;
import net.minecraft.network.packet.s2c.play.PlaySoundFromEntityS2CPacket;
import net.minecraft.network.packet.s2c.play.PlaySoundS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerAbilitiesS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerActionResponseS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerListHeaderS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerListS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerPositionLookS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerRemoveS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerRespawnS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerRotationS2CPacket;
import net.minecraft.network.packet.s2c.play.PlayerSpawnPositionS2CPacket;
import net.minecraft.network.packet.s2c.play.ProfilelessChatMessageS2CPacket;
import net.minecraft.network.packet.s2c.play.ProjectilePowerS2CPacket;
import net.minecraft.network.packet.s2c.play.RecipeBookAddS2CPacket;
import net.minecraft.network.packet.s2c.play.RecipeBookRemoveS2CPacket;
import net.minecraft.network.packet.s2c.play.RecipeBookSettingsS2CPacket;
import net.minecraft.network.packet.s2c.play.RemoveEntityStatusEffectS2CPacket;
import net.minecraft.network.packet.s2c.play.RemoveMessageS2CPacket;
import net.minecraft.network.packet.s2c.play.ScoreboardDisplayS2CPacket;
import net.minecraft.network.packet.s2c.play.ScoreboardObjectiveUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.ScoreboardScoreResetS2CPacket;
import net.minecraft.network.packet.s2c.play.ScoreboardScoreUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.ScreenHandlerPropertyUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.ScreenHandlerSlotUpdateS2CPacket;
import net.minecraft.network.packet.s2c.play.SelectAdvancementTabS2CPacket;
import net.minecraft.network.packet.s2c.play.ServerMetadataS2CPacket;
import net.minecraft.network.packet.s2c.play.SetCameraEntityS2CPacket;
import net.minecraft.network.packet.s2c.play.SetCursorItemS2CPacket;
import net.minecraft.network.packet.s2c.play.SetPlayerInventoryS2CPacket;
import net.minecraft.network.packet.s2c.play.SetTradeOffersS2CPacket;
import net.minecraft.network.packet.s2c.play.SignEditorOpenS2CPacket;
import net.minecraft.network.packet.s2c.play.SimulationDistanceS2CPacket;
import net.minecraft.network.packet.s2c.play.StartChunkSendS2CPacket;
import net.minecraft.network.packet.s2c.play.StatisticsS2CPacket;
import net.minecraft.network.packet.s2c.play.StopSoundS2CPacket;
import net.minecraft.network.packet.s2c.play.SubtitleS2CPacket;
import net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket;
import net.minecraft.network.packet.s2c.play.TeamS2CPacket;
import net.minecraft.network.packet.s2c.play.TestInstanceBlockStatusS2CPacket;
import net.minecraft.network.packet.s2c.play.TickStepS2CPacket;
import net.minecraft.network.packet.s2c.play.TitleFadeS2CPacket;
import net.minecraft.network.packet.s2c.play.TitleS2CPacket;
import net.minecraft.network.packet.s2c.play.UnloadChunkS2CPacket;
import net.minecraft.network.packet.s2c.play.UpdateSelectedSlotS2CPacket;
import net.minecraft.network.packet.s2c.play.UpdateTickRateS2CPacket;
import net.minecraft.network.packet.s2c.play.VehicleMoveS2CPacket;
import net.minecraft.network.packet.s2c.play.WaypointS2CPacket;
import net.minecraft.network.packet.s2c.play.WorldBorderCenterChangedS2CPacket;
import net.minecraft.network.packet.s2c.play.WorldBorderInitializeS2CPacket;
import net.minecraft.network.packet.s2c.play.WorldBorderInterpolateSizeS2CPacket;
import net.minecraft.network.packet.s2c.play.WorldBorderSizeChangedS2CPacket;
import net.minecraft.network.packet.s2c.play.WorldBorderWarningBlocksChangedS2CPacket;
import net.minecraft.network.packet.s2c.play.WorldBorderWarningTimeChangedS2CPacket;
import net.minecraft.network.packet.s2c.play.WorldEventS2CPacket;
import net.minecraft.network.packet.s2c.play.WorldTimeUpdateS2CPacket;
import net.minecraft.util.Identifier;

public class PlayPackets {
    final static public PacketType<BundleS2CPacket> BUNDLE = PlayPackets.s2c("bundle");
    final static public PacketType<BundleDelimiterS2CPacket> BUNDLE_DELIMITER = PlayPackets.s2c("bundle_delimiter");
    final static public PacketType<EntitySpawnS2CPacket> ADD_ENTITY = PlayPackets.s2c("add_entity");
    final static public PacketType<EntityAnimationS2CPacket> ANIMATE = PlayPackets.s2c("animate");
    final static public PacketType<StatisticsS2CPacket> AWARD_STATS = PlayPackets.s2c("award_stats");
    final static public PacketType<PlayerActionResponseS2CPacket> BLOCK_CHANGED_ACK = PlayPackets.s2c("block_changed_ack");
    final static public PacketType<BlockBreakingProgressS2CPacket> BLOCK_DESTRUCTION = PlayPackets.s2c("block_destruction");
    final static public PacketType<BlockEntityUpdateS2CPacket> BLOCK_ENTITY_DATA = PlayPackets.s2c("block_entity_data");
    final static public PacketType<BlockEventS2CPacket> BLOCK_EVENT = PlayPackets.s2c("block_event");
    final static public PacketType<BlockUpdateS2CPacket> BLOCK_UPDATE = PlayPackets.s2c("block_update");
    final static public PacketType<BossBarS2CPacket> BOSS_EVENT = PlayPackets.s2c("boss_event");
    final static public PacketType<DifficultyS2CPacket> CHANGE_DIFFICULTY_S2C = PlayPackets.s2c("change_difficulty");
    final static public PacketType<ChunkSentS2CPacket> CHUNK_BATCH_FINISHED = PlayPackets.s2c("chunk_batch_finished");
    final static public PacketType<StartChunkSendS2CPacket> CHUNK_BATCH_START = PlayPackets.s2c("chunk_batch_start");
    final static public PacketType<ChunkBiomeDataS2CPacket> CHUNKS_BIOMES = PlayPackets.s2c("chunks_biomes");
    final static public PacketType<ClearTitleS2CPacket> CLEAR_TITLES = PlayPackets.s2c("clear_titles");
    final static public PacketType<CommandSuggestionsS2CPacket> COMMAND_SUGGESTIONS = PlayPackets.s2c("command_suggestions");
    final static public PacketType<CommandTreeS2CPacket> COMMANDS = PlayPackets.s2c("commands");
    final static public PacketType<CloseScreenS2CPacket> CONTAINER_CLOSE_S2C = PlayPackets.s2c("container_close");
    final static public PacketType<InventoryS2CPacket> CONTAINER_SET_CONTENT = PlayPackets.s2c("container_set_content");
    final static public PacketType<ScreenHandlerPropertyUpdateS2CPacket> CONTAINER_SET_DATA = PlayPackets.s2c("container_set_data");
    final static public PacketType<ScreenHandlerSlotUpdateS2CPacket> CONTAINER_SET_SLOT = PlayPackets.s2c("container_set_slot");
    final static public PacketType<CooldownUpdateS2CPacket> COOLDOWN = PlayPackets.s2c("cooldown");
    final static public PacketType<ChatSuggestionsS2CPacket> CUSTOM_CHAT_COMPLETIONS = PlayPackets.s2c("custom_chat_completions");
    final static public PacketType<EntityDamageS2CPacket> DAMAGE_EVENT = PlayPackets.s2c("damage_event");
    final static public PacketType<DebugSampleS2CPacket> DEBUG_SAMPLE = PlayPackets.s2c("debug_sample");
    final static public PacketType<RemoveMessageS2CPacket> DELETE_CHAT = PlayPackets.s2c("delete_chat");
    final static public PacketType<ProfilelessChatMessageS2CPacket> DISGUISED_CHAT = PlayPackets.s2c("disguised_chat");
    final static public PacketType<EntityStatusS2CPacket> ENTITY_EVENT = PlayPackets.s2c("entity_event");
    final static public PacketType<EntityPositionSyncS2CPacket> ENTITY_POSITION_SYNC = PlayPackets.s2c("entity_position_sync");
    final static public PacketType<ExplosionS2CPacket> EXPLODE = PlayPackets.s2c("explode");
    final static public PacketType<UnloadChunkS2CPacket> FORGET_LEVEL_CHUNK = PlayPackets.s2c("forget_level_chunk");
    final static public PacketType<GameStateChangeS2CPacket> GAME_EVENT = PlayPackets.s2c("game_event");
    final static public PacketType<OpenHorseScreenS2CPacket> HORSE_SCREEN_OPEN = PlayPackets.s2c("horse_screen_open");
    final static public PacketType<DamageTiltS2CPacket> HURT_ANIMATION = PlayPackets.s2c("hurt_animation");
    final static public PacketType<WorldBorderInitializeS2CPacket> INITIALIZE_BORDER = PlayPackets.s2c("initialize_border");
    final static public PacketType<ChunkDataS2CPacket> LEVEL_CHUNK_WITH_LIGHT = PlayPackets.s2c("level_chunk_with_light");
    final static public PacketType<WorldEventS2CPacket> LEVEL_EVENT = PlayPackets.s2c("level_event");
    final static public PacketType<ParticleS2CPacket> LEVEL_PARTICLES = PlayPackets.s2c("level_particles");
    final static public PacketType<LightUpdateS2CPacket> LIGHT_UPDATE = PlayPackets.s2c("light_update");
    final static public PacketType<GameJoinS2CPacket> LOGIN = PlayPackets.s2c("login");
    final static public PacketType<MapUpdateS2CPacket> MAP_ITEM_DATA = PlayPackets.s2c("map_item_data");
    final static public PacketType<SetTradeOffersS2CPacket> MERCHANT_OFFERS = PlayPackets.s2c("merchant_offers");
    final static public PacketType<EntityS2CPacket.MoveRelative> MOVE_ENTITY_POS = PlayPackets.s2c("move_entity_pos");
    final static public PacketType<EntityS2CPacket.RotateAndMoveRelative> MOVE_ENTITY_POS_ROT = PlayPackets.s2c("move_entity_pos_rot");
    final static public PacketType<MoveMinecartAlongTrackS2CPacket> MOVE_MINECART_ALONG_TRACK = PlayPackets.s2c("move_minecart_along_track");
    final static public PacketType<EntityS2CPacket.Rotate> MOVE_ENTITY_ROT = PlayPackets.s2c("move_entity_rot");
    final static public PacketType<VehicleMoveS2CPacket> MOVE_VEHICLE_S2C = PlayPackets.s2c("move_vehicle");
    final static public PacketType<OpenWrittenBookS2CPacket> OPEN_BOOK = PlayPackets.s2c("open_book");
    final static public PacketType<OpenScreenS2CPacket> OPEN_SCREEN = PlayPackets.s2c("open_screen");
    final static public PacketType<SignEditorOpenS2CPacket> OPEN_SIGN_EDITOR = PlayPackets.s2c("open_sign_editor");
    final static public PacketType<CraftFailedResponseS2CPacket> PLACE_GHOST_RECIPE = PlayPackets.s2c("place_ghost_recipe");
    final static public PacketType<PlayerAbilitiesS2CPacket> PLAYER_ABILITIES_S2C = PlayPackets.s2c("player_abilities");
    final static public PacketType<ChatMessageS2CPacket> PLAYER_CHAT = PlayPackets.s2c("player_chat");
    final static public PacketType<EndCombatS2CPacket> PLAYER_COMBAT_END = PlayPackets.s2c("player_combat_end");
    final static public PacketType<EnterCombatS2CPacket> PLAYER_COMBAT_ENTER = PlayPackets.s2c("player_combat_enter");
    final static public PacketType<DeathMessageS2CPacket> PLAYER_COMBAT_KILL = PlayPackets.s2c("player_combat_kill");
    final static public PacketType<PlayerRemoveS2CPacket> PLAYER_INFO_REMOVE = PlayPackets.s2c("player_info_remove");
    final static public PacketType<PlayerListS2CPacket> PLAYER_INFO_UPDATE = PlayPackets.s2c("player_info_update");
    final static public PacketType<LookAtS2CPacket> PLAYER_LOOK_AT = PlayPackets.s2c("player_look_at");
    final static public PacketType<PlayerPositionLookS2CPacket> PLAYER_POSITION = PlayPackets.s2c("player_position");
    final static public PacketType<PlayerRotationS2CPacket> PLAYER_ROTATION = PlayPackets.s2c("player_rotation");
    final static public PacketType<RecipeBookAddS2CPacket> RECIPE_BOOK_ADD = PlayPackets.s2c("recipe_book_add");
    final static public PacketType<RecipeBookRemoveS2CPacket> RECIPE_BOOK_REMOVE = PlayPackets.s2c("recipe_book_remove");
    final static public PacketType<RecipeBookSettingsS2CPacket> RECIPE_BOOK_SETTINGS = PlayPackets.s2c("recipe_book_settings");
    final static public PacketType<EntitiesDestroyS2CPacket> REMOVE_ENTITIES = PlayPackets.s2c("remove_entities");
    final static public PacketType<RemoveEntityStatusEffectS2CPacket> REMOVE_MOB_EFFECT = PlayPackets.s2c("remove_mob_effect");
    final static public PacketType<PlayerRespawnS2CPacket> RESPAWN = PlayPackets.s2c("respawn");
    final static public PacketType<EntitySetHeadYawS2CPacket> ROTATE_HEAD = PlayPackets.s2c("rotate_head");
    final static public PacketType<ChunkDeltaUpdateS2CPacket> SECTION_BLOCKS_UPDATE = PlayPackets.s2c("section_blocks_update");
    final static public PacketType<SelectAdvancementTabS2CPacket> SELECT_ADVANCEMENTS_TAB = PlayPackets.s2c("select_advancements_tab");
    final static public PacketType<ServerMetadataS2CPacket> SERVER_DATA = PlayPackets.s2c("server_data");
    final static public PacketType<OverlayMessageS2CPacket> SET_ACTION_BAR_TEXT = PlayPackets.s2c("set_action_bar_text");
    final static public PacketType<WorldBorderCenterChangedS2CPacket> SET_BORDER_CENTER = PlayPackets.s2c("set_border_center");
    final static public PacketType<WorldBorderInterpolateSizeS2CPacket> SET_BORDER_LERP_SIZE = PlayPackets.s2c("set_border_lerp_size");
    final static public PacketType<WorldBorderSizeChangedS2CPacket> SET_BORDER_SIZE = PlayPackets.s2c("set_border_size");
    final static public PacketType<WorldBorderWarningTimeChangedS2CPacket> SET_BORDER_WARNING_DELAY = PlayPackets.s2c("set_border_warning_delay");
    final static public PacketType<WorldBorderWarningBlocksChangedS2CPacket> SET_BORDER_WARNING_DISTANCE = PlayPackets.s2c("set_border_warning_distance");
    final static public PacketType<SetCameraEntityS2CPacket> SET_CAMERA = PlayPackets.s2c("set_camera");
    final static public PacketType<ChunkRenderDistanceCenterS2CPacket> SET_CHUNK_CACHE_CENTER = PlayPackets.s2c("set_chunk_cache_center");
    final static public PacketType<ChunkLoadDistanceS2CPacket> SET_CHUNK_CACHE_RADIUS = PlayPackets.s2c("set_chunk_cache_radius");
    final static public PacketType<PlayerSpawnPositionS2CPacket> SET_DEFAULT_SPAWN_POSITION = PlayPackets.s2c("set_default_spawn_position");
    final static public PacketType<ScoreboardDisplayS2CPacket> SET_DISPLAY_OBJECTIVE = PlayPackets.s2c("set_display_objective");
    final static public PacketType<EntityTrackerUpdateS2CPacket> SET_ENTITY_DATA = PlayPackets.s2c("set_entity_data");
    final static public PacketType<EntityAttachS2CPacket> SET_ENTITY_LINK = PlayPackets.s2c("set_entity_link");
    final static public PacketType<EntityVelocityUpdateS2CPacket> SET_ENTITY_MOTION = PlayPackets.s2c("set_entity_motion");
    final static public PacketType<EntityEquipmentUpdateS2CPacket> SET_EQUIPMENT = PlayPackets.s2c("set_equipment");
    final static public PacketType<ExperienceBarUpdateS2CPacket> SET_EXPERIENCE = PlayPackets.s2c("set_experience");
    final static public PacketType<HealthUpdateS2CPacket> SET_HEALTH = PlayPackets.s2c("set_health");
    final static public PacketType<UpdateSelectedSlotS2CPacket> SET_CARRIED_ITEM_S2C = PlayPackets.s2c("set_held_slot");
    final static public PacketType<ScoreboardObjectiveUpdateS2CPacket> SET_OBJECTIVE = PlayPackets.s2c("set_objective");
    final static public PacketType<EntityPassengersSetS2CPacket> SET_PASSENGERS = PlayPackets.s2c("set_passengers");
    final static public PacketType<TeamS2CPacket> SET_PLAYER_TEAM = PlayPackets.s2c("set_player_team");
    final static public PacketType<ScoreboardScoreUpdateS2CPacket> SET_SCORE = PlayPackets.s2c("set_score");
    final static public PacketType<SimulationDistanceS2CPacket> SET_SIMULATION_DISTANCE = PlayPackets.s2c("set_simulation_distance");
    final static public PacketType<SubtitleS2CPacket> SET_SUBTITLE_TEXT = PlayPackets.s2c("set_subtitle_text");
    final static public PacketType<WorldTimeUpdateS2CPacket> SET_TIME = PlayPackets.s2c("set_time");
    final static public PacketType<TitleS2CPacket> SET_TITLE_TEXT = PlayPackets.s2c("set_title_text");
    final static public PacketType<TitleFadeS2CPacket> SET_TITLES_ANIMATION = PlayPackets.s2c("set_titles_animation");
    final static public PacketType<PlaySoundFromEntityS2CPacket> SOUND_ENTITY = PlayPackets.s2c("sound_entity");
    final static public PacketType<PlaySoundS2CPacket> SOUND = PlayPackets.s2c("sound");
    final static public PacketType<EnterReconfigurationS2CPacket> START_CONFIGURATION = PlayPackets.s2c("start_configuration");
    final static public PacketType<StopSoundS2CPacket> STOP_SOUND = PlayPackets.s2c("stop_sound");
    final static public PacketType<GameMessageS2CPacket> SYSTEM_CHAT = PlayPackets.s2c("system_chat");
    final static public PacketType<PlayerListHeaderS2CPacket> TAB_LIST = PlayPackets.s2c("tab_list");
    final static public PacketType<NbtQueryResponseS2CPacket> TAG_QUERY = PlayPackets.s2c("tag_query");
    final static public PacketType<ItemPickupAnimationS2CPacket> TAKE_ITEM_ENTITY = PlayPackets.s2c("take_item_entity");
    final static public PacketType<EntityPositionS2CPacket> TELEPORT_ENTITY = PlayPackets.s2c("teleport_entity");
    final static public PacketType<TestInstanceBlockStatusS2CPacket> TEST_INSTANCE_BLOCK_STATUS = PlayPackets.s2c("test_instance_block_status");
    final static public PacketType<AdvancementUpdateS2CPacket> UPDATE_ADVANCEMENTS = PlayPackets.s2c("update_advancements");
    final static public PacketType<EntityAttributesS2CPacket> UPDATE_ATTRIBUTES = PlayPackets.s2c("update_attributes");
    final static public PacketType<EntityStatusEffectS2CPacket> UPDATE_MOB_EFFECT = PlayPackets.s2c("update_mob_effect");
    final static public PacketType<SynchronizeRecipesS2CPacket> UPDATE_RECIPES = PlayPackets.s2c("update_recipes");
    final static public PacketType<ProjectilePowerS2CPacket> PROJECTILE_POWER = PlayPackets.s2c("projectile_power");
    final static public PacketType<WaypointS2CPacket> WAYPOINT = PlayPackets.s2c("waypoint");
    final static public PacketType<TeleportConfirmC2SPacket> ACCEPT_TELEPORTATION = PlayPackets.c2s("accept_teleportation");
    final static public PacketType<QueryBlockNbtC2SPacket> BLOCK_ENTITY_TAG_QUERY = PlayPackets.c2s("block_entity_tag_query");
    final static public PacketType<BundleItemSelectedC2SPacket> BUNDLE_ITEM_SELECTED = PlayPackets.c2s("bundle_item_selected");
    final static public PacketType<UpdateDifficultyC2SPacket> CHANGE_DIFFICULTY_C2S = PlayPackets.c2s("change_difficulty");
    final static public PacketType<ChangeGameModeC2SPacket> CHANGE_GAME_MODE = PlayPackets.c2s("change_game_mode");
    final static public PacketType<MessageAcknowledgmentC2SPacket> CHAT_ACK = PlayPackets.c2s("chat_ack");
    final static public PacketType<CommandExecutionC2SPacket> CHAT_COMMAND = PlayPackets.c2s("chat_command");
    final static public PacketType<ChatCommandSignedC2SPacket> CHAT_COMMAND_SIGNED = PlayPackets.c2s("chat_command_signed");
    final static public PacketType<ChatMessageC2SPacket> CHAT = PlayPackets.c2s("chat");
    final static public PacketType<PlayerSessionC2SPacket> CHAT_SESSION_UPDATE = PlayPackets.c2s("chat_session_update");
    final static public PacketType<AcknowledgeChunksC2SPacket> CHUNK_BATCH_RECEIVED = PlayPackets.c2s("chunk_batch_received");
    final static public PacketType<ClientStatusC2SPacket> CLIENT_COMMAND = PlayPackets.c2s("client_command");
    final static public PacketType<ClientTickEndC2SPacket> CLIENT_TICK_END = PlayPackets.c2s("client_tick_end");
    final static public PacketType<RequestCommandCompletionsC2SPacket> COMMAND_SUGGESTION = PlayPackets.c2s("command_suggestion");
    final static public PacketType<AcknowledgeReconfigurationC2SPacket> CONFIGURATION_ACKNOWLEDGED = PlayPackets.c2s("configuration_acknowledged");
    final static public PacketType<ButtonClickC2SPacket> CONTAINER_BUTTON_CLICK = PlayPackets.c2s("container_button_click");
    final static public PacketType<ClickSlotC2SPacket> CONTAINER_CLICK = PlayPackets.c2s("container_click");
    final static public PacketType<CloseHandledScreenC2SPacket> CONTAINER_CLOSE_C2S = PlayPackets.c2s("container_close");
    final static public PacketType<SlotChangedStateC2SPacket> CONTAINER_SLOT_STATE_CHANGED = PlayPackets.c2s("container_slot_state_changed");
    final static public PacketType<DebugSampleSubscriptionC2SPacket> DEBUG_SAMPLE_SUBSCRIPTION = PlayPackets.c2s("debug_sample_subscription");
    final static public PacketType<BookUpdateC2SPacket> EDIT_BOOK = PlayPackets.c2s("edit_book");
    final static public PacketType<QueryEntityNbtC2SPacket> ENTITY_TAG_QUERY = PlayPackets.c2s("entity_tag_query");
    final static public PacketType<PlayerInteractEntityC2SPacket> INTERACT = PlayPackets.c2s("interact");
    final static public PacketType<JigsawGeneratingC2SPacket> JIGSAW_GENERATE = PlayPackets.c2s("jigsaw_generate");
    final static public PacketType<UpdateDifficultyLockC2SPacket> LOCK_DIFFICULTY = PlayPackets.c2s("lock_difficulty");
    final static public PacketType<PlayerMoveC2SPacket.PositionAndOnGround> MOVE_PLAYER_POS = PlayPackets.c2s("move_player_pos");
    final static public PacketType<PlayerMoveC2SPacket.Full> MOVE_PLAYER_POS_ROT = PlayPackets.c2s("move_player_pos_rot");
    final static public PacketType<PlayerMoveC2SPacket.LookAndOnGround> MOVE_PLAYER_ROT = PlayPackets.c2s("move_player_rot");
    final static public PacketType<PlayerMoveC2SPacket.OnGroundOnly> MOVE_PLAYER_STATUS_ONLY = PlayPackets.c2s("move_player_status_only");
    final static public PacketType<VehicleMoveC2SPacket> MOVE_VEHICLE_C2S = PlayPackets.c2s("move_vehicle");
    final static public PacketType<BoatPaddleStateC2SPacket> PADDLE_BOAT = PlayPackets.c2s("paddle_boat");
    final static public PacketType<PickItemFromBlockC2SPacket> PICK_ITEM_FROM_BLOCK = PlayPackets.c2s("pick_item_from_block");
    final static public PacketType<PickItemFromEntityC2SPacket> PICK_ITEM_FROM_ENTITY = PlayPackets.c2s("pick_item_from_entity");
    final static public PacketType<CraftRequestC2SPacket> PLACE_RECIPE = PlayPackets.c2s("place_recipe");
    final static public PacketType<UpdatePlayerAbilitiesC2SPacket> PLAYER_ABILITIES_C2S = PlayPackets.c2s("player_abilities");
    final static public PacketType<PlayerActionC2SPacket> PLAYER_ACTION = PlayPackets.c2s("player_action");
    final static public PacketType<ClientCommandC2SPacket> PLAYER_COMMAND = PlayPackets.c2s("player_command");
    final static public PacketType<PlayerInputC2SPacket> PLAYER_INPUT = PlayPackets.c2s("player_input");
    final static public PacketType<PlayerLoadedC2SPacket> PLAYER_LOADED = PlayPackets.c2s("player_loaded");
    final static public PacketType<RecipeCategoryOptionsC2SPacket> RECIPE_BOOK_CHANGE_SETTINGS = PlayPackets.c2s("recipe_book_change_settings");
    final static public PacketType<RecipeBookDataC2SPacket> RECIPE_BOOK_SEEN_RECIPE = PlayPackets.c2s("recipe_book_seen_recipe");
    final static public PacketType<RenameItemC2SPacket> RENAME_ITEM = PlayPackets.c2s("rename_item");
    final static public PacketType<AdvancementTabC2SPacket> SEEN_ADVANCEMENTS = PlayPackets.c2s("seen_advancements");
    final static public PacketType<SelectMerchantTradeC2SPacket> SELECT_TRADE = PlayPackets.c2s("select_trade");
    final static public PacketType<UpdateBeaconC2SPacket> SET_BEACON = PlayPackets.c2s("set_beacon");
    final static public PacketType<UpdateSelectedSlotC2SPacket> SET_CARRIED_ITEM_C2S = PlayPackets.c2s("set_carried_item");
    final static public PacketType<UpdateCommandBlockC2SPacket> SET_COMMAND_BLOCK = PlayPackets.c2s("set_command_block");
    final static public PacketType<UpdateCommandBlockMinecartC2SPacket> SET_COMMAND_MINECART = PlayPackets.c2s("set_command_minecart");
    final static public PacketType<CreativeInventoryActionC2SPacket> SET_CREATIVE_MODE_SLOT = PlayPackets.c2s("set_creative_mode_slot");
    final static public PacketType<UpdateJigsawC2SPacket> SET_JIGSAW_BLOCK = PlayPackets.c2s("set_jigsaw_block");
    final static public PacketType<UpdateStructureBlockC2SPacket> SET_STRUCTURE_BLOCK = PlayPackets.c2s("set_structure_block");
    final static public PacketType<SetTestBlockC2SPacket> SET_TEST_BLOCK = PlayPackets.c2s("set_test_block");
    final static public PacketType<TestInstanceBlockActionC2SPacket> TEST_INSTANCE_BLOCK_ACTION = PlayPackets.c2s("test_instance_block_action");
    final static public PacketType<UpdateSignC2SPacket> SIGN_UPDATE = PlayPackets.c2s("sign_update");
    final static public PacketType<HandSwingC2SPacket> SWING = PlayPackets.c2s("swing");
    final static public PacketType<SpectatorTeleportC2SPacket> TELEPORT_TO_ENTITY = PlayPackets.c2s("teleport_to_entity");
    final static public PacketType<PlayerInteractBlockC2SPacket> USE_ITEM_ON = PlayPackets.c2s("use_item_on");
    final static public PacketType<PlayerInteractItemC2SPacket> USE_ITEM = PlayPackets.c2s("use_item");
    final static public PacketType<ScoreboardScoreResetS2CPacket> RESET_SCORE = PlayPackets.s2c("reset_score");
    final static public PacketType<UpdateTickRateS2CPacket> TICKING_STATE = PlayPackets.s2c("ticking_state");
    final static public PacketType<TickStepS2CPacket> TICKING_STEP = PlayPackets.s2c("ticking_step");
    final static public PacketType<SetCursorItemS2CPacket> SET_CURSOR_ITEM = PlayPackets.s2c("set_cursor_item");
    final static public PacketType<SetPlayerInventoryS2CPacket> SET_PLAYER_INVENTORY = PlayPackets.s2c("set_player_inventory");

    private static <T extends Packet<ClientPlayPacketListener>> PacketType<T> s2c(String id) {
        return new PacketType(NetworkSide.CLIENTBOUND, Identifier.ofVanilla(id));
    }

    private static <T extends Packet<ServerPlayPacketListener>> PacketType<T> c2s(String id) {
        return new PacketType(NetworkSide.SERVERBOUND, Identifier.ofVanilla(id));
    }
}

