/*
 * Decompiled with CFR 0.152.
 */
package net.minecraft.registry.tag;

import net.minecraft.item.Item;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;

public final class ItemTags {
    final static public TagKey<Item> WOOL = ItemTags.of("wool");
    final static public TagKey<Item> PLANKS = ItemTags.of("planks");
    final static public TagKey<Item> STONE_BRICKS = ItemTags.of("stone_bricks");
    final static public TagKey<Item> WOODEN_BUTTONS = ItemTags.of("wooden_buttons");
    final static public TagKey<Item> STONE_BUTTONS = ItemTags.of("stone_buttons");
    final static public TagKey<Item> BUTTONS = ItemTags.of("buttons");
    final static public TagKey<Item> WOOL_CARPETS = ItemTags.of("wool_carpets");
    final static public TagKey<Item> WOODEN_DOORS = ItemTags.of("wooden_doors");
    final static public TagKey<Item> WOODEN_STAIRS = ItemTags.of("wooden_stairs");
    final static public TagKey<Item> WOODEN_SLABS = ItemTags.of("wooden_slabs");
    final static public TagKey<Item> WOODEN_FENCES = ItemTags.of("wooden_fences");
    final static public TagKey<Item> FENCE_GATES = ItemTags.of("fence_gates");
    final static public TagKey<Item> WOODEN_PRESSURE_PLATES = ItemTags.of("wooden_pressure_plates");
    final static public TagKey<Item> DOORS = ItemTags.of("doors");
    final static public TagKey<Item> SAPLINGS = ItemTags.of("saplings");
    final static public TagKey<Item> BAMBOO_BLOCKS = ItemTags.of("bamboo_blocks");
    final static public TagKey<Item> OAK_LOGS = ItemTags.of("oak_logs");
    final static public TagKey<Item> DARK_OAK_LOGS = ItemTags.of("dark_oak_logs");
    final static public TagKey<Item> PALE_OAK_LOGS = ItemTags.of("pale_oak_logs");
    final static public TagKey<Item> BIRCH_LOGS = ItemTags.of("birch_logs");
    final static public TagKey<Item> ACACIA_LOGS = ItemTags.of("acacia_logs");
    final static public TagKey<Item> SPRUCE_LOGS = ItemTags.of("spruce_logs");
    final static public TagKey<Item> MANGROVE_LOGS = ItemTags.of("mangrove_logs");
    final static public TagKey<Item> JUNGLE_LOGS = ItemTags.of("jungle_logs");
    final static public TagKey<Item> CHERRY_LOGS = ItemTags.of("cherry_logs");
    final static public TagKey<Item> CRIMSON_STEMS = ItemTags.of("crimson_stems");
    final static public TagKey<Item> WARPED_STEMS = ItemTags.of("warped_stems");
    final static public TagKey<Item> WART_BLOCKS = ItemTags.of("wart_blocks");
    final static public TagKey<Item> LOGS_THAT_BURN = ItemTags.of("logs_that_burn");
    final static public TagKey<Item> LOGS = ItemTags.of("logs");
    final static public TagKey<Item> SAND = ItemTags.of("sand");
    final static public TagKey<Item> SMELTS_TO_GLASS = ItemTags.of("smelts_to_glass");
    final static public TagKey<Item> SLABS = ItemTags.of("slabs");
    final static public TagKey<Item> WALLS = ItemTags.of("walls");
    final static public TagKey<Item> STAIRS = ItemTags.of("stairs");
    final static public TagKey<Item> ANVIL = ItemTags.of("anvil");
    final static public TagKey<Item> RAILS = ItemTags.of("rails");
    final static public TagKey<Item> LEAVES = ItemTags.of("leaves");
    final static public TagKey<Item> WOODEN_TRAPDOORS = ItemTags.of("wooden_trapdoors");
    final static public TagKey<Item> TRAPDOORS = ItemTags.of("trapdoors");
    final static public TagKey<Item> SMALL_FLOWERS = ItemTags.of("small_flowers");
    final static public TagKey<Item> FLOWERS = ItemTags.of("flowers");
    final static public TagKey<Item> BEDS = ItemTags.of("beds");
    final static public TagKey<Item> FENCES = ItemTags.of("fences");
    final static public TagKey<Item> SOUL_FIRE_BASE_BLOCKS = ItemTags.of("soul_fire_base_blocks");
    final static public TagKey<Item> CANDLES = ItemTags.of("candles");
    final static public TagKey<Item> DAMPENS_VIBRATIONS = ItemTags.of("dampens_vibrations");
    final static public TagKey<Item> GOLD_ORES = ItemTags.of("gold_ores");
    final static public TagKey<Item> IRON_ORES = ItemTags.of("iron_ores");
    final static public TagKey<Item> DIAMOND_ORES = ItemTags.of("diamond_ores");
    final static public TagKey<Item> REDSTONE_ORES = ItemTags.of("redstone_ores");
    final static public TagKey<Item> LAPIS_ORES = ItemTags.of("lapis_ores");
    final static public TagKey<Item> COAL_ORES = ItemTags.of("coal_ores");
    final static public TagKey<Item> EMERALD_ORES = ItemTags.of("emerald_ores");
    final static public TagKey<Item> COPPER_ORES = ItemTags.of("copper_ores");
    final static public TagKey<Item> DIRT = ItemTags.of("dirt");
    final static public TagKey<Item> TERRACOTTA = ItemTags.of("terracotta");
    final static public TagKey<Item> COMPLETES_FIND_TREE_TUTORIAL = ItemTags.of("completes_find_tree_tutorial");
    final static public TagKey<Item> SHULKER_BOXES = ItemTags.of("shulker_boxes");
    final static public TagKey<Item> SIGNS = ItemTags.of("signs");
    final static public TagKey<Item> HANGING_SIGNS = ItemTags.of("hanging_signs");
    final static public TagKey<Item> BEE_FOOD = ItemTags.of("bee_food");
    final static public TagKey<Item> BANNERS = ItemTags.of("banners");
    final static public TagKey<Item> PIGLIN_REPELLENTS = ItemTags.of("piglin_repellents");
    final static public TagKey<Item> PIGLIN_LOVED = ItemTags.of("piglin_loved");
    final static public TagKey<Item> IGNORED_BY_PIGLIN_BABIES = ItemTags.of("ignored_by_piglin_babies");
    final static public TagKey<Item> PIGLIN_SAFE_ARMOR = ItemTags.of("piglin_safe_armor");
    final static public TagKey<Item> DUPLICATES_ALLAYS = ItemTags.of("duplicates_allays");
    final static public TagKey<Item> BREWING_FUEL = ItemTags.of("brewing_fuel");
    final static public TagKey<Item> EGGS = ItemTags.of("eggs");
    final static public TagKey<Item> MEAT = ItemTags.of("meat");
    final static public TagKey<Item> SNIFFER_FOOD = ItemTags.of("sniffer_food");
    final static public TagKey<Item> PIGLIN_FOOD = ItemTags.of("piglin_food");
    final static public TagKey<Item> FOX_FOOD = ItemTags.of("fox_food");
    final static public TagKey<Item> COW_FOOD = ItemTags.of("cow_food");
    final static public TagKey<Item> GOAT_FOOD = ItemTags.of("goat_food");
    final static public TagKey<Item> SHEEP_FOOD = ItemTags.of("sheep_food");
    final static public TagKey<Item> WOLF_FOOD = ItemTags.of("wolf_food");
    final static public TagKey<Item> CAT_FOOD = ItemTags.of("cat_food");
    final static public TagKey<Item> HORSE_FOOD = ItemTags.of("horse_food");
    final static public TagKey<Item> HORSE_TEMPT_ITEMS = ItemTags.of("horse_tempt_items");
    final static public TagKey<Item> HARNESSES = ItemTags.of("harnesses");
    final static public TagKey<Item> HAPPY_GHAST_FOOD = ItemTags.of("happy_ghast_food");
    final static public TagKey<Item> HAPPY_GHAST_TEMPT_ITEMS = ItemTags.of("happy_ghast_tempt_items");
    final static public TagKey<Item> CAMEL_FOOD = ItemTags.of("camel_food");
    final static public TagKey<Item> ARMADILLO_FOOD = ItemTags.of("armadillo_food");
    final static public TagKey<Item> CHICKEN_FOOD = ItemTags.of("chicken_food");
    final static public TagKey<Item> FROG_FOOD = ItemTags.of("frog_food");
    final static public TagKey<Item> HOGLIN_FOOD = ItemTags.of("hoglin_food");
    final static public TagKey<Item> LLAMA_FOOD = ItemTags.of("llama_food");
    final static public TagKey<Item> LLAMA_TEMPT_ITEMS = ItemTags.of("llama_tempt_items");
    final static public TagKey<Item> OCELOT_FOOD = ItemTags.of("ocelot_food");
    final static public TagKey<Item> PANDA_FOOD = ItemTags.of("panda_food");
    final static public TagKey<Item> PANDA_EATS_FROM_GROUND = ItemTags.of("panda_eats_from_ground");
    final static public TagKey<Item> PIG_FOOD = ItemTags.of("pig_food");
    final static public TagKey<Item> RABBIT_FOOD = ItemTags.of("rabbit_food");
    final static public TagKey<Item> STRIDER_FOOD = ItemTags.of("strider_food");
    final static public TagKey<Item> STRIDER_TEMPT_ITEMS = ItemTags.of("strider_tempt_items");
    final static public TagKey<Item> TURTLE_FOOD = ItemTags.of("turtle_food");
    final static public TagKey<Item> PARROT_FOOD = ItemTags.of("parrot_food");
    final static public TagKey<Item> PARROT_POISONOUS_FOOD = ItemTags.of("parrot_poisonous_food");
    final static public TagKey<Item> AXOLOTL_FOOD = ItemTags.of("axolotl_food");
    final static public TagKey<Item> NON_FLAMMABLE_WOOD = ItemTags.of("non_flammable_wood");
    final static public TagKey<Item> BOATS = ItemTags.of("boats");
    final static public TagKey<Item> CHEST_BOATS = ItemTags.of("chest_boats");
    final static public TagKey<Item> FISHES = ItemTags.of("fishes");
    final static public TagKey<Item> CREEPER_DROP_MUSIC_DISCS = ItemTags.of("creeper_drop_music_discs");
    final static public TagKey<Item> COALS = ItemTags.of("coals");
    final static public TagKey<Item> ARROWS = ItemTags.of("arrows");
    final static public TagKey<Item> LECTERN_BOOKS = ItemTags.of("lectern_books");
    final static public TagKey<Item> BOOKSHELF_BOOKS = ItemTags.of("bookshelf_books");
    final static public TagKey<Item> BEACON_PAYMENT_ITEMS = ItemTags.of("beacon_payment_items");
    final static public TagKey<Item> WOODEN_TOOL_MATERIALS = ItemTags.of("wooden_tool_materials");
    final static public TagKey<Item> STONE_TOOL_MATERIALS = ItemTags.of("stone_tool_materials");
    final static public TagKey<Item> IRON_TOOL_MATERIALS = ItemTags.of("iron_tool_materials");
    final static public TagKey<Item> GOLD_TOOL_MATERIALS = ItemTags.of("gold_tool_materials");
    final static public TagKey<Item> DIAMOND_TOOL_MATERIALS = ItemTags.of("diamond_tool_materials");
    final static public TagKey<Item> NETHERITE_TOOL_MATERIALS = ItemTags.of("netherite_tool_materials");
    final static public TagKey<Item> REPAIRS_LEATHER_ARMOR = ItemTags.of("repairs_leather_armor");
    final static public TagKey<Item> REPAIRS_CHAIN_ARMOR = ItemTags.of("repairs_chain_armor");
    final static public TagKey<Item> REPAIRS_IRON_ARMOR = ItemTags.of("repairs_iron_armor");
    final static public TagKey<Item> REPAIRS_GOLD_ARMOR = ItemTags.of("repairs_gold_armor");
    final static public TagKey<Item> REPAIRS_DIAMOND_ARMOR = ItemTags.of("repairs_diamond_armor");
    final static public TagKey<Item> REPAIRS_NETHERITE_ARMOR = ItemTags.of("repairs_netherite_armor");
    final static public TagKey<Item> REPAIRS_TURTLE_HELMET = ItemTags.of("repairs_turtle_helmet");
    final static public TagKey<Item> REPAIRS_WOLF_ARMOR = ItemTags.of("repairs_wolf_armor");
    final static public TagKey<Item> STONE_CRAFTING_MATERIALS = ItemTags.of("stone_crafting_materials");
    final static public TagKey<Item> FREEZE_IMMUNE_WEARABLES = ItemTags.of("freeze_immune_wearables");
    final static public TagKey<Item> CLUSTER_MAX_HARVESTABLES = ItemTags.of("cluster_max_harvestables");
    final static public TagKey<Item> COMPASSES = ItemTags.of("compasses");
    final static public TagKey<Item> CREEPER_IGNITERS = ItemTags.of("creeper_igniters");
    final static public TagKey<Item> NOTEBLOCK_TOP_INSTRUMENTS = ItemTags.of("noteblock_top_instruments");
    final static public TagKey<Item> FOOT_ARMOR = ItemTags.of("foot_armor");
    final static public TagKey<Item> LEG_ARMOR = ItemTags.of("leg_armor");
    final static public TagKey<Item> CHEST_ARMOR = ItemTags.of("chest_armor");
    final static public TagKey<Item> HEAD_ARMOR = ItemTags.of("head_armor");
    final static public TagKey<Item> SKULLS = ItemTags.of("skulls");
    final static public TagKey<Item> TRIMMABLE_ARMOR = ItemTags.of("trimmable_armor");
    final static public TagKey<Item> TRIM_MATERIALS = ItemTags.of("trim_materials");
    final static public TagKey<Item> DECORATED_POT_SHERDS = ItemTags.of("decorated_pot_sherds");
    final static public TagKey<Item> DECORATED_POT_INGREDIENTS = ItemTags.of("decorated_pot_ingredients");
    final static public TagKey<Item> SWORDS = ItemTags.of("swords");
    final static public TagKey<Item> AXES = ItemTags.of("axes");
    final static public TagKey<Item> HOES = ItemTags.of("hoes");
    final static public TagKey<Item> PICKAXES = ItemTags.of("pickaxes");
    final static public TagKey<Item> SHOVELS = ItemTags.of("shovels");
    final static public TagKey<Item> BREAKS_DECORATED_POTS = ItemTags.of("breaks_decorated_pots");
    final static public TagKey<Item> VILLAGER_PLANTABLE_SEEDS = ItemTags.of("villager_plantable_seeds");
    final static public TagKey<Item> VILLAGER_PICKS_UP = ItemTags.of("villager_picks_up");
    final static public TagKey<Item> DYEABLE = ItemTags.of("dyeable");
    final static public TagKey<Item> FURNACE_MINECART_FUEL = ItemTags.of("furnace_minecart_fuel");
    final static public TagKey<Item> BUNDLES = ItemTags.of("bundles");
    final static public TagKey<Item> BOOK_CLONING_TARGET = ItemTags.of("book_cloning_target");
    final static public TagKey<Item> SKELETON_PREFERRED_WEAPONS = ItemTags.of("skeleton_preferred_weapons");
    final static public TagKey<Item> DROWNED_PREFERRED_WEAPONS = ItemTags.of("drowned_preferred_weapons");
    final static public TagKey<Item> PIGLIN_PREFERRED_WEAPONS = ItemTags.of("piglin_preferred_weapons");
    final static public TagKey<Item> PILLAGER_PREFERRED_WEAPONS = ItemTags.of("pillager_preferred_weapons");
    final static public TagKey<Item> WITHER_SKELETON_DISLIKED_WEAPONS = ItemTags.of("wither_skeleton_disliked_weapons");
    final static public TagKey<Item> FOOT_ARMOR_ENCHANTABLE = ItemTags.of("enchantable/foot_armor");
    final static public TagKey<Item> LEG_ARMOR_ENCHANTABLE = ItemTags.of("enchantable/leg_armor");
    final static public TagKey<Item> CHEST_ARMOR_ENCHANTABLE = ItemTags.of("enchantable/chest_armor");
    final static public TagKey<Item> HEAD_ARMOR_ENCHANTABLE = ItemTags.of("enchantable/head_armor");
    final static public TagKey<Item> ARMOR_ENCHANTABLE = ItemTags.of("enchantable/armor");
    final static public TagKey<Item> SWORD_ENCHANTABLE = ItemTags.of("enchantable/sword");
    final static public TagKey<Item> FIRE_ASPECT_ENCHANTABLE = ItemTags.of("enchantable/fire_aspect");
    final static public TagKey<Item> SHARP_WEAPON_ENCHANTABLE = ItemTags.of("enchantable/sharp_weapon");
    final static public TagKey<Item> WEAPON_ENCHANTABLE = ItemTags.of("enchantable/weapon");
    final static public TagKey<Item> MINING_ENCHANTABLE = ItemTags.of("enchantable/mining");
    final static public TagKey<Item> MINING_LOOT_ENCHANTABLE = ItemTags.of("enchantable/mining_loot");
    final static public TagKey<Item> FISHING_ENCHANTABLE = ItemTags.of("enchantable/fishing");
    final static public TagKey<Item> TRIDENT_ENCHANTABLE = ItemTags.of("enchantable/trident");
    final static public TagKey<Item> DURABILITY_ENCHANTABLE = ItemTags.of("enchantable/durability");
    final static public TagKey<Item> BOW_ENCHANTABLE = ItemTags.of("enchantable/bow");
    final static public TagKey<Item> EQUIPPABLE_ENCHANTABLE = ItemTags.of("enchantable/equippable");
    final static public TagKey<Item> CROSSBOW_ENCHANTABLE = ItemTags.of("enchantable/crossbow");
    final static public TagKey<Item> VANISHING_ENCHANTABLE = ItemTags.of("enchantable/vanishing");
    final static public TagKey<Item> MACE_ENCHANTABLE = ItemTags.of("enchantable/mace");
    final static public TagKey<Item> MAP_INVISIBILITY_EQUIPMENT = ItemTags.of("map_invisibility_equipment");
    final static public TagKey<Item> GAZE_DISGUISE_EQUIPMENT = ItemTags.of("gaze_disguise_equipment");

    private ItemTags() {
    }

    private static TagKey<Item> of(String id) {
        return TagKey.of(RegistryKeys.ITEM, Identifier.ofVanilla(id));
    }
}

