/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  com.google.common.collect.ImmutableMap$Builder
 *  net.fabricmc.api.EnvType
 *  net.fabricmc.api.Environment
 */
package net.minecraft.client.render.entity.model;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.block.WoodType;
import net.minecraft.client.model.Dilation;
import net.minecraft.client.model.TexturedModelData;
import net.minecraft.client.render.block.entity.BedBlockEntityRenderer;
import net.minecraft.client.render.block.entity.ConduitBlockEntityRenderer;
import net.minecraft.client.render.block.entity.DecoratedPotBlockEntityRenderer;
import net.minecraft.client.render.block.entity.HangingSignBlockEntityRenderer;
import net.minecraft.client.render.block.entity.SignBlockEntityRenderer;
import net.minecraft.client.render.block.entity.model.BannerBlockModel;
import net.minecraft.client.render.block.entity.model.BannerFlagBlockModel;
import net.minecraft.client.render.block.entity.model.BellBlockModel;
import net.minecraft.client.render.block.entity.model.ChestBlockModel;
import net.minecraft.client.render.entity.DragonEntityModel;
import net.minecraft.client.render.entity.WitherSkullEntityRenderer;
import net.minecraft.client.render.entity.model.AbstractHorseEntityModel;
import net.minecraft.client.render.entity.model.AllayEntityModel;
import net.minecraft.client.render.entity.model.ArmadilloEntityModel;
import net.minecraft.client.render.entity.model.ArmorEntityModel;
import net.minecraft.client.render.entity.model.ArmorStandArmorEntityModel;
import net.minecraft.client.render.entity.model.ArmorStandEntityModel;
import net.minecraft.client.render.entity.model.ArrowEntityModel;
import net.minecraft.client.render.entity.model.AxolotlEntityModel;
import net.minecraft.client.render.entity.model.BatEntityModel;
import net.minecraft.client.render.entity.model.BeeEntityModel;
import net.minecraft.client.render.entity.model.BipedEntityModel;
import net.minecraft.client.render.entity.model.BlazeEntityModel;
import net.minecraft.client.render.entity.model.BoatEntityModel;
import net.minecraft.client.render.entity.model.BoggedEntityModel;
import net.minecraft.client.render.entity.model.BookModel;
import net.minecraft.client.render.entity.model.BreezeEntityModel;
import net.minecraft.client.render.entity.model.CamelEntityModel;
import net.minecraft.client.render.entity.model.CamelSaddleEntityModel;
import net.minecraft.client.render.entity.model.CatEntityModel;
import net.minecraft.client.render.entity.model.ChickenEntityModel;
import net.minecraft.client.render.entity.model.CodEntityModel;
import net.minecraft.client.render.entity.model.ColdChickenEntityModel;
import net.minecraft.client.render.entity.model.ColdCowEntityModel;
import net.minecraft.client.render.entity.model.ColdPigEntityModel;
import net.minecraft.client.render.entity.model.CowEntityModel;
import net.minecraft.client.render.entity.model.CreakingEntityModel;
import net.minecraft.client.render.entity.model.CreeperEntityModel;
import net.minecraft.client.render.entity.model.Deadmau5EarsEntityModel;
import net.minecraft.client.render.entity.model.DolphinEntityModel;
import net.minecraft.client.render.entity.model.DonkeyEntityModel;
import net.minecraft.client.render.entity.model.DragonHeadEntityModel;
import net.minecraft.client.render.entity.model.DrownedEntityModel;
import net.minecraft.client.render.entity.model.ElytraEntityModel;
import net.minecraft.client.render.entity.model.EndCrystalEntityModel;
import net.minecraft.client.render.entity.model.EndermanEntityModel;
import net.minecraft.client.render.entity.model.EndermiteEntityModel;
import net.minecraft.client.render.entity.model.EntityModelLayer;
import net.minecraft.client.render.entity.model.EntityModelLayers;
import net.minecraft.client.render.entity.model.EvokerFangsEntityModel;
import net.minecraft.client.render.entity.model.FelineEntityModel;
import net.minecraft.client.render.entity.model.FoxEntityModel;
import net.minecraft.client.render.entity.model.FrogEntityModel;
import net.minecraft.client.render.entity.model.GhastEntityModel;
import net.minecraft.client.render.entity.model.GoatEntityModel;
import net.minecraft.client.render.entity.model.GuardianEntityModel;
import net.minecraft.client.render.entity.model.HappyGhastEntityModel;
import net.minecraft.client.render.entity.model.HappyGhastHarnessEntityModel;
import net.minecraft.client.render.entity.model.HoglinEntityModel;
import net.minecraft.client.render.entity.model.HorseSaddleEntityModel;
import net.minecraft.client.render.entity.model.IllagerEntityModel;
import net.minecraft.client.render.entity.model.IronGolemEntityModel;
import net.minecraft.client.render.entity.model.LargePufferfishEntityModel;
import net.minecraft.client.render.entity.model.LargeTropicalFishEntityModel;
import net.minecraft.client.render.entity.model.LeashKnotEntityModel;
import net.minecraft.client.render.entity.model.LlamaEntityModel;
import net.minecraft.client.render.entity.model.LlamaSpitEntityModel;
import net.minecraft.client.render.entity.model.MagmaCubeEntityModel;
import net.minecraft.client.render.entity.model.MediumPufferfishEntityModel;
import net.minecraft.client.render.entity.model.MinecartEntityModel;
import net.minecraft.client.render.entity.model.ModelTransformer;
import net.minecraft.client.render.entity.model.PandaEntityModel;
import net.minecraft.client.render.entity.model.ParrotEntityModel;
import net.minecraft.client.render.entity.model.PhantomEntityModel;
import net.minecraft.client.render.entity.model.PigEntityModel;
import net.minecraft.client.render.entity.model.PiglinEntityModel;
import net.minecraft.client.render.entity.model.PiglinHeadEntityModel;
import net.minecraft.client.render.entity.model.PlayerCapeModel;
import net.minecraft.client.render.entity.model.PlayerEntityModel;
import net.minecraft.client.render.entity.model.PolarBearEntityModel;
import net.minecraft.client.render.entity.model.RabbitEntityModel;
import net.minecraft.client.render.entity.model.RaftEntityModel;
import net.minecraft.client.render.entity.model.RavagerEntityModel;
import net.minecraft.client.render.entity.model.SalmonEntityModel;
import net.minecraft.client.render.entity.model.SheepEntityModel;
import net.minecraft.client.render.entity.model.SheepWoolEntityModel;
import net.minecraft.client.render.entity.model.ShieldEntityModel;
import net.minecraft.client.render.entity.model.ShulkerBulletEntityModel;
import net.minecraft.client.render.entity.model.ShulkerEntityModel;
import net.minecraft.client.render.entity.model.SilverfishEntityModel;
import net.minecraft.client.render.entity.model.SkeletonEntityModel;
import net.minecraft.client.render.entity.model.SkullEntityModel;
import net.minecraft.client.render.entity.model.SlimeEntityModel;
import net.minecraft.client.render.entity.model.SmallPufferfishEntityModel;
import net.minecraft.client.render.entity.model.SmallTropicalFishEntityModel;
import net.minecraft.client.render.entity.model.SnifferEntityModel;
import net.minecraft.client.render.entity.model.SnowGolemEntityModel;
import net.minecraft.client.render.entity.model.SpiderEntityModel;
import net.minecraft.client.render.entity.model.SquidEntityModel;
import net.minecraft.client.render.entity.model.StingerModel;
import net.minecraft.client.render.entity.model.StriderEntityModel;
import net.minecraft.client.render.entity.model.TadpoleEntityModel;
import net.minecraft.client.render.entity.model.TridentEntityModel;
import net.minecraft.client.render.entity.model.TridentRiptideEntityModel;
import net.minecraft.client.render.entity.model.TurtleEntityModel;
import net.minecraft.client.render.entity.model.VexEntityModel;
import net.minecraft.client.render.entity.model.VillagerResemblingModel;
import net.minecraft.client.render.entity.model.WardenEntityModel;
import net.minecraft.client.render.entity.model.WarmCowEntityModel;
import net.minecraft.client.render.entity.model.WindChargeEntityModel;
import net.minecraft.client.render.entity.model.WitchEntityModel;
import net.minecraft.client.render.entity.model.WitherEntityModel;
import net.minecraft.client.render.entity.model.WolfEntityModel;
import net.minecraft.client.render.entity.model.ZombieVillagerEntityModel;

@Environment(value=EnvType.CLIENT)
public class EntityModels {
    final static private Dilation FISH_PATTERN_DILATION = new Dilation(0.008f);
    final static private Dilation ARMOR_DILATION = new Dilation(1.0f);
    final static private Dilation HAT_DILATION = new Dilation(0.5f);

    public static Map<EntityModelLayer, TexturedModelData> getModels() {
        ImmutableMap.Builder builder = ImmutableMap.builder();
        TexturedModelData texturedModelData = TexturedModelData.of(BipedEntityModel.getModelData(Dilation.NONE, 0.0f), 64, 64);
        TexturedModelData texturedModelData2 = TexturedModelData.of(ArmorEntityModel.getModelData(ARMOR_DILATION), 64, 32);
        TexturedModelData texturedModelData3 = TexturedModelData.of(ArmorEntityModel.getModelData(new Dilation(1.02f)), 64, 32);
        TexturedModelData texturedModelData4 = TexturedModelData.of(ArmorEntityModel.getModelData(HAT_DILATION), 64, 32);
        TexturedModelData texturedModelData5 = MinecartEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData6 = SkullEntityModel.getSkullTexturedModelData();
        TexturedModelData texturedModelData7 = TexturedModelData.of(AbstractHorseEntityModel.getModelData(Dilation.NONE), 64, 64);
        TexturedModelData texturedModelData8 = TexturedModelData.of(AbstractHorseEntityModel.getBabyHorseModelData(Dilation.NONE), 64, 64);
        TexturedModelData texturedModelData9 = HorseSaddleEntityModel.getTexturedModelData(false);
        TexturedModelData texturedModelData10 = HorseSaddleEntityModel.getTexturedModelData(true);
        ModelTransformer modelTransformer = ModelTransformer.scaling(0.9375f);
        TexturedModelData texturedModelData11 = IllagerEntityModel.getTexturedModelData().transform(modelTransformer);
        TexturedModelData texturedModelData12 = AxolotlEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData13 = BeeEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData14 = CowEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData15 = ColdChickenEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData16 = ColdCowEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData17 = ColdPigEntityModel.getTexturedModelData(Dilation.NONE);
        TexturedModelData texturedModelData18 = ElytraEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData19 = TexturedModelData.of(FelineEntityModel.getModelData(Dilation.NONE), 64, 32);
        TexturedModelData texturedModelData20 = texturedModelData19.transform(FelineEntityModel.BABY_TRANSFORMER);
        TexturedModelData texturedModelData21 = TexturedModelData.of(FelineEntityModel.getModelData(new Dilation(0.01f)), 64, 32);
        TexturedModelData texturedModelData22 = TexturedModelData.of(PiglinEntityModel.getModelData(Dilation.NONE), 64, 64);
        TexturedModelData texturedModelData23 = TexturedModelData.of(PiglinHeadEntityModel.getModelData(), 64, 64);
        TexturedModelData texturedModelData24 = SkullEntityModel.getHeadTexturedModelData();
        TexturedModelData texturedModelData25 = LlamaEntityModel.getTexturedModelData(Dilation.NONE);
        TexturedModelData texturedModelData26 = LlamaEntityModel.getTexturedModelData(new Dilation(0.5f));
        TexturedModelData texturedModelData27 = StriderEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData28 = HoglinEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData29 = HoglinEntityModel.getBabyTexturedModelData();
        TexturedModelData texturedModelData30 = SkeletonEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData31 = TexturedModelData.of(VillagerResemblingModel.getModelData(), 64, 64).transform(modelTransformer);
        TexturedModelData texturedModelData32 = SpiderEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData33 = ArmadilloEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData34 = CamelEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData35 = CamelSaddleEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData36 = ChickenEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData37 = GoatEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData38 = PandaEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData39 = PigEntityModel.getTexturedModelData(Dilation.NONE);
        TexturedModelData texturedModelData40 = PigEntityModel.getTexturedModelData(new Dilation(0.5f));
        TexturedModelData texturedModelData41 = SheepEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData42 = SheepWoolEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData43 = SnifferEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData44 = TurtleEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData45 = WarmCowEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData46 = TexturedModelData.of(WolfEntityModel.getTexturedModelData(Dilation.NONE), 64, 32);
        TexturedModelData texturedModelData47 = TexturedModelData.of(WolfEntityModel.getTexturedModelData(new Dilation(0.2f)), 64, 32);
        TexturedModelData texturedModelData48 = ZombieVillagerEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData49 = ArmorStandEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData50 = ArmorStandArmorEntityModel.getTexturedModelData(HAT_DILATION);
        TexturedModelData texturedModelData51 = ArmorStandArmorEntityModel.getTexturedModelData(ARMOR_DILATION);
        TexturedModelData texturedModelData52 = DrownedEntityModel.getTexturedModelData(Dilation.NONE);
        TexturedModelData texturedModelData53 = DrownedEntityModel.getTexturedModelData(new Dilation(0.25f));
        TexturedModelData texturedModelData54 = SquidEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData55 = DolphinEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData56 = SalmonEntityModel.getTexturedModelData();
        builder.put((Object)EntityModelLayers.ALLAY, (Object)AllayEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.ARMADILLO, (Object)texturedModelData33);
        builder.put((Object)EntityModelLayers.ARMADILLO_BABY, (Object)texturedModelData33.transform(ArmadilloEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ARMOR_STAND, (Object)texturedModelData49);
        builder.put((Object)EntityModelLayers.ARMOR_STAND_INNER_ARMOR, (Object)texturedModelData50);
        builder.put((Object)EntityModelLayers.ARMOR_STAND_OUTER_ARMOR, (Object)texturedModelData51);
        builder.put((Object)EntityModelLayers.ARMOR_STAND_SMALL, (Object)texturedModelData49.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ARMOR_STAND_SMALL_INNER_ARMOR, (Object)texturedModelData50.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ARMOR_STAND_SMALL_OUTER_ARMOR, (Object)texturedModelData51.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ARROW, (Object)ArrowEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.AXOLOTL, (Object)texturedModelData12);
        builder.put((Object)EntityModelLayers.AXOLOTL_BABY, (Object)texturedModelData12.transform(AxolotlEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.STANDING_BANNER, (Object)BannerBlockModel.getTexturedModelData(true));
        builder.put((Object)EntityModelLayers.WALL_BANNER, (Object)BannerBlockModel.getTexturedModelData(false));
        builder.put((Object)EntityModelLayers.STANDING_BANNER_FLAG, (Object)BannerFlagBlockModel.getTexturedModelData(true));
        builder.put((Object)EntityModelLayers.WALL_BANNER_FLAG, (Object)BannerFlagBlockModel.getTexturedModelData(false));
        builder.put((Object)EntityModelLayers.BAT, (Object)BatEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.BED_FOOT, (Object)BedBlockEntityRenderer.getFootTexturedModelData());
        builder.put((Object)EntityModelLayers.BED_HEAD, (Object)BedBlockEntityRenderer.getHeadTexturedModelData());
        builder.put((Object)EntityModelLayers.BEE, (Object)texturedModelData13);
        builder.put((Object)EntityModelLayers.BEE_BABY, (Object)texturedModelData13.transform(BeeEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.BEE_STINGER, (Object)StingerModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.BELL, (Object)BellBlockModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.BLAZE, (Object)BlazeEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.BOAT, (Object)BoatEntityModel.getBaseTexturedModelData());
        builder.put((Object)EntityModelLayers.BOGGED, (Object)BoggedEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.BOGGED_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.BOGGED_OUTER_ARMOR, (Object)texturedModelData2);
        builder.put((Object)EntityModelLayers.BOGGED_OUTER, (Object)TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.2f), 0.0f), 64, 32));
        builder.put((Object)EntityModelLayers.BOOK, (Object)BookModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.BREEZE, (Object)BreezeEntityModel.getTexturedModelData(32, 32));
        builder.put((Object)EntityModelLayers.BREEZE_WIND, (Object)BreezeEntityModel.getTexturedModelData(128, 128));
        builder.put((Object)EntityModelLayers.CAT, (Object)texturedModelData19.transform(CatEntityModel.CAT_TRANSFORMER));
        builder.put((Object)EntityModelLayers.CAT_BABY, (Object)texturedModelData20.transform(CatEntityModel.CAT_TRANSFORMER));
        builder.put((Object)EntityModelLayers.CAT_COLLAR, (Object)texturedModelData21.transform(CatEntityModel.CAT_TRANSFORMER));
        builder.put((Object)EntityModelLayers.CAT_BABY_COLLAR, (Object)texturedModelData21.transform(FelineEntityModel.BABY_TRANSFORMER).transform(CatEntityModel.CAT_TRANSFORMER));
        builder.put((Object)EntityModelLayers.CAMEL, (Object)texturedModelData34);
        builder.put((Object)EntityModelLayers.CAMEL_BABY, (Object)texturedModelData34.transform(CamelEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.CAMEL_SADDLE, (Object)texturedModelData35);
        builder.put((Object)EntityModelLayers.CAMEL_BABY_SADDLE, (Object)texturedModelData35.transform(CamelEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.CAVE_SPIDER, (Object)texturedModelData32.transform(ModelTransformer.scaling(0.7f)));
        builder.put((Object)EntityModelLayers.CHEST, (Object)ChestBlockModel.getSingleTexturedModelData());
        builder.put((Object)EntityModelLayers.CHEST_MINECART, (Object)texturedModelData5);
        builder.put((Object)EntityModelLayers.CHICKEN, (Object)texturedModelData36);
        builder.put((Object)EntityModelLayers.CHICKEN_BABY, (Object)texturedModelData36.transform(ChickenEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.COD, (Object)CodEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.COLD_CHICKEN, (Object)texturedModelData15);
        builder.put((Object)EntityModelLayers.COLD_CHICKEN_BABY, (Object)texturedModelData15.transform(ChickenEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.COLD_COW, (Object)texturedModelData16);
        builder.put((Object)EntityModelLayers.COLD_COW_BABY, (Object)texturedModelData16.transform(CowEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.COLD_PIG, (Object)texturedModelData17);
        builder.put((Object)EntityModelLayers.COLD_PIG_BABY, (Object)texturedModelData17.transform(PigEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.COMMAND_BLOCK_MINECART, (Object)texturedModelData5);
        builder.put((Object)EntityModelLayers.CONDUIT_EYE, (Object)ConduitBlockEntityRenderer.getEyeTexturedModelData());
        builder.put((Object)EntityModelLayers.CONDUIT_WIND, (Object)ConduitBlockEntityRenderer.getWindTexturedModelData());
        builder.put((Object)EntityModelLayers.CONDUIT_SHELL, (Object)ConduitBlockEntityRenderer.getShellTexturedModelData());
        builder.put((Object)EntityModelLayers.CONDUIT, (Object)ConduitBlockEntityRenderer.getPlainTexturedModelData());
        builder.put((Object)EntityModelLayers.COW, (Object)texturedModelData14);
        builder.put((Object)EntityModelLayers.COW_BABY, (Object)texturedModelData14.transform(CowEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.CREAKING, (Object)CreakingEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.CREEPER, (Object)CreeperEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put((Object)EntityModelLayers.CREEPER_ARMOR, (Object)CreeperEntityModel.getTexturedModelData(new Dilation(2.0f)));
        builder.put((Object)EntityModelLayers.CREEPER_HEAD, (Object)texturedModelData6);
        builder.put((Object)EntityModelLayers.DECORATED_POT_BASE, (Object)DecoratedPotBlockEntityRenderer.getTopBottomNeckTexturedModelData());
        builder.put((Object)EntityModelLayers.DECORATED_POT_SIDES, (Object)DecoratedPotBlockEntityRenderer.getSidesTexturedModelData());
        builder.put((Object)EntityModelLayers.DOLPHIN, (Object)texturedModelData55);
        builder.put((Object)EntityModelLayers.DOLPHIN_BABY, (Object)texturedModelData55.transform(DolphinEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.DONKEY, (Object)DonkeyEntityModel.getTexturedModelData(0.87f));
        builder.put((Object)EntityModelLayers.DONKEY_BABY, (Object)DonkeyEntityModel.getBabyTexturedModelData(0.87f));
        builder.put((Object)EntityModelLayers.DONKEY_SADDLE, (Object)DonkeyEntityModel.getSaddleTexturedModelData(0.87f, false));
        builder.put((Object)EntityModelLayers.DONKEY_BABY_SADDLE, (Object)DonkeyEntityModel.getSaddleTexturedModelData(0.87f, true));
        builder.put((Object)EntityModelLayers.DOUBLE_CHEST_LEFT, (Object)ChestBlockModel.getDoubleChestLeftTexturedBlockData());
        builder.put((Object)EntityModelLayers.DOUBLE_CHEST_RIGHT, (Object)ChestBlockModel.getDoubleChestRightTexturedBlockData());
        builder.put((Object)EntityModelLayers.DRAGON_SKULL, (Object)DragonHeadEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.DROWNED, (Object)texturedModelData52);
        builder.put((Object)EntityModelLayers.DROWNED_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.DROWNED_OUTER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.DROWNED_OUTER, (Object)texturedModelData53);
        builder.put((Object)EntityModelLayers.DROWNED_BABY, (Object)texturedModelData52.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.DROWNED_BABY_INNER_ARMOR, (Object)texturedModelData4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.DROWNED_BABY_OUTER_ARMOR, (Object)texturedModelData4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.DROWNED_BABY_OUTER, (Object)texturedModelData53.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ELDER_GUARDIAN, (Object)GuardianEntityModel.getElderTexturedModelData());
        builder.put((Object)EntityModelLayers.ELYTRA, (Object)texturedModelData18);
        builder.put((Object)EntityModelLayers.ELYTRA_BABY, (Object)texturedModelData18.transform(ElytraEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ENDERMAN, (Object)EndermanEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.ENDERMITE, (Object)EndermiteEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.ENDER_DRAGON, (Object)DragonEntityModel.createTexturedModelData());
        builder.put((Object)EntityModelLayers.END_CRYSTAL, (Object)EndCrystalEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.EVOKER, (Object)texturedModelData11);
        builder.put((Object)EntityModelLayers.EVOKER_FANGS, (Object)EvokerFangsEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.FOX, (Object)FoxEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.FOX_BABY, (Object)FoxEntityModel.getTexturedModelData().transform(FoxEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.FROG, (Object)FrogEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.FURNACE_MINECART, (Object)texturedModelData5);
        builder.put((Object)EntityModelLayers.GHAST, (Object)GhastEntityModel.getTexturedModelData());
        ModelTransformer modelTransformer2 = ModelTransformer.scaling(6.0f);
        builder.put((Object)EntityModelLayers.GIANT, (Object)texturedModelData.transform(modelTransformer2));
        builder.put((Object)EntityModelLayers.GIANT_INNER_ARMOR, (Object)texturedModelData4.transform(modelTransformer2));
        builder.put((Object)EntityModelLayers.GIANT_OUTER_ARMOR, (Object)texturedModelData2.transform(modelTransformer2));
        builder.put((Object)EntityModelLayers.GLOW_SQUID, (Object)texturedModelData54);
        builder.put((Object)EntityModelLayers.GLOW_SQUID_BABY, (Object)texturedModelData54.transform(SquidEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.GOAT, (Object)texturedModelData37);
        builder.put((Object)EntityModelLayers.GOAT_BABY, (Object)texturedModelData37.transform(GoatEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.GUARDIAN, (Object)GuardianEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.HAPPY_GHAST, (Object)HappyGhastEntityModel.getTexturedModelData(false, Dilation.NONE));
        builder.put((Object)EntityModelLayers.HAPPY_GHAST_BABY, (Object)HappyGhastEntityModel.getTexturedModelData(true, Dilation.NONE).transform(HappyGhastEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.HAPPY_GHAST_HARNESS, (Object)HappyGhastHarnessEntityModel.getTexturedModelData(false));
        builder.put((Object)EntityModelLayers.HAPPY_GHAST_BABY_HARNESS, (Object)HappyGhastHarnessEntityModel.getTexturedModelData(true).transform(HappyGhastEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.HAPPY_GHAST_ROPES, (Object)HappyGhastEntityModel.getTexturedModelData(false, new Dilation(0.2f)));
        builder.put((Object)EntityModelLayers.HAPPY_GHAST_BABY_ROPES, (Object)HappyGhastEntityModel.getTexturedModelData(true, new Dilation(0.2f)).transform(HappyGhastEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.HOGLIN, (Object)texturedModelData28);
        builder.put((Object)EntityModelLayers.HOGLIN_BABY, (Object)texturedModelData29);
        builder.put((Object)EntityModelLayers.HOPPER_MINECART, (Object)texturedModelData5);
        ModelTransformer modelTransformer3 = ModelTransformer.scaling(1.1f);
        builder.put((Object)EntityModelLayers.HORSE, (Object)texturedModelData7.transform(modelTransformer3));
        builder.put((Object)EntityModelLayers.HORSE_BABY, (Object)texturedModelData8.transform(modelTransformer3));
        builder.put((Object)EntityModelLayers.HORSE_ARMOR, (Object)TexturedModelData.of(AbstractHorseEntityModel.getModelData(new Dilation(0.1f)), 64, 64).transform(modelTransformer3));
        builder.put((Object)EntityModelLayers.HORSE_ARMOR_BABY, (Object)TexturedModelData.of(AbstractHorseEntityModel.getBabyHorseModelData(new Dilation(0.1f)), 64, 64).transform(modelTransformer3));
        builder.put((Object)EntityModelLayers.HORSE_SADDLE, (Object)texturedModelData9.transform(modelTransformer3));
        builder.put((Object)EntityModelLayers.HORSE_BABY_SADDLE, (Object)texturedModelData10.transform(modelTransformer3));
        ModelTransformer modelTransformer4 = ModelTransformer.scaling(1.0625f);
        builder.put((Object)EntityModelLayers.HUSK, (Object)texturedModelData.transform(modelTransformer4));
        builder.put((Object)EntityModelLayers.HUSK_INNER_ARMOR, (Object)texturedModelData4.transform(modelTransformer4));
        builder.put((Object)EntityModelLayers.HUSK_OUTER_ARMOR, (Object)texturedModelData2.transform(modelTransformer4));
        builder.put((Object)EntityModelLayers.HUSK_BABY, (Object)texturedModelData.transform(BipedEntityModel.BABY_TRANSFORMER).transform(modelTransformer4));
        builder.put((Object)EntityModelLayers.HUSK_BABY_INNER_ARMOR, (Object)texturedModelData4.transform(BipedEntityModel.BABY_TRANSFORMER).transform(modelTransformer4));
        builder.put((Object)EntityModelLayers.HUSK_BABY_OUTER_ARMOR, (Object)texturedModelData2.transform(BipedEntityModel.BABY_TRANSFORMER).transform(modelTransformer4));
        builder.put((Object)EntityModelLayers.ILLUSIONER, (Object)texturedModelData11);
        builder.put((Object)EntityModelLayers.IRON_GOLEM, (Object)IronGolemEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.LEASH_KNOT, (Object)LeashKnotEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.LLAMA, (Object)texturedModelData25);
        builder.put((Object)EntityModelLayers.LLAMA_BABY, (Object)texturedModelData25.transform(LlamaEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.LLAMA_DECOR, (Object)texturedModelData26);
        builder.put((Object)EntityModelLayers.LLAMA_BABY_DECOR, (Object)texturedModelData26.transform(LlamaEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.LLAMA_SPIT, (Object)LlamaSpitEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.MAGMA_CUBE, (Object)MagmaCubeEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.MINECART, (Object)texturedModelData5);
        builder.put((Object)EntityModelLayers.MOOSHROOM, (Object)texturedModelData14);
        builder.put((Object)EntityModelLayers.MOOSHROOM_BABY, (Object)texturedModelData14.transform(CowEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.MULE, (Object)DonkeyEntityModel.getTexturedModelData(0.92f));
        builder.put((Object)EntityModelLayers.MULE_BABY, (Object)DonkeyEntityModel.getBabyTexturedModelData(0.92f));
        builder.put((Object)EntityModelLayers.MULE_SADDLE, (Object)DonkeyEntityModel.getSaddleTexturedModelData(0.92f, false));
        builder.put((Object)EntityModelLayers.MULE_BABY_SADDLE, (Object)DonkeyEntityModel.getSaddleTexturedModelData(0.92f, true));
        builder.put((Object)EntityModelLayers.OCELOT, (Object)texturedModelData19);
        builder.put((Object)EntityModelLayers.OCELOT_BABY, (Object)texturedModelData20);
        builder.put((Object)EntityModelLayers.PANDA, (Object)texturedModelData38);
        builder.put((Object)EntityModelLayers.PANDA_BABY, (Object)texturedModelData38.transform(PandaEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.PARROT, (Object)ParrotEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.PHANTOM, (Object)PhantomEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.PIG, (Object)texturedModelData39);
        builder.put((Object)EntityModelLayers.PIG_BABY, (Object)texturedModelData39.transform(PigEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.PIG_SADDLE, (Object)texturedModelData40);
        builder.put((Object)EntityModelLayers.PIG_BABY_SADDLE, (Object)texturedModelData40.transform(PigEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.PIGLIN, (Object)texturedModelData22);
        builder.put((Object)EntityModelLayers.PIGLIN_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.PIGLIN_OUTER_ARMOR, (Object)texturedModelData3);
        builder.put((Object)EntityModelLayers.PIGLIN_BRUTE, (Object)texturedModelData22);
        builder.put((Object)EntityModelLayers.PIGLIN_BRUTE_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, (Object)texturedModelData3);
        builder.put((Object)EntityModelLayers.PIGLIN_BABY, (Object)texturedModelData22.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.PIGLIN_BABY_INNER_ARMOR, (Object)texturedModelData4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.PIGLIN_BABY_OUTER_ARMOR, (Object)texturedModelData3.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.PIGLIN_HEAD, (Object)texturedModelData23);
        builder.put((Object)EntityModelLayers.PILLAGER, (Object)texturedModelData11);
        builder.put((Object)EntityModelLayers.PLAYER, (Object)TexturedModelData.of(PlayerEntityModel.getTexturedModelData(Dilation.NONE, false), 64, 64));
        builder.put((Object)EntityModelLayers.PLAYER_EARS, (Object)Deadmau5EarsEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.PLAYER_CAPE, (Object)PlayerCapeModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.PLAYER_HEAD, (Object)texturedModelData24);
        builder.put((Object)EntityModelLayers.PLAYER_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.PLAYER_OUTER_ARMOR, (Object)texturedModelData2);
        builder.put((Object)EntityModelLayers.PLAYER_SLIM, (Object)TexturedModelData.of(PlayerEntityModel.getTexturedModelData(Dilation.NONE, true), 64, 64));
        builder.put((Object)EntityModelLayers.PLAYER_SLIM_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.PLAYER_SLIM_OUTER_ARMOR, (Object)texturedModelData2);
        builder.put((Object)EntityModelLayers.SPIN_ATTACK, (Object)TridentRiptideEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.POLAR_BEAR, (Object)PolarBearEntityModel.getTexturedModelData(false));
        builder.put((Object)EntityModelLayers.POLAR_BEAR_BABY, (Object)PolarBearEntityModel.getTexturedModelData(true));
        builder.put((Object)EntityModelLayers.PUFFERFISH_BIG, (Object)LargePufferfishEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.PUFFERFISH_MEDIUM, (Object)MediumPufferfishEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.PUFFERFISH_SMALL, (Object)SmallPufferfishEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.RABBIT, (Object)RabbitEntityModel.getTexturedModelData(false));
        builder.put((Object)EntityModelLayers.RABBIT_BABY, (Object)RabbitEntityModel.getTexturedModelData(true));
        builder.put((Object)EntityModelLayers.RAVAGER, (Object)RavagerEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.SALMON, (Object)texturedModelData56);
        builder.put((Object)EntityModelLayers.SALMON_SMALL, (Object)texturedModelData56.transform(SalmonEntityModel.SMALL_TRANSFORMER));
        builder.put((Object)EntityModelLayers.SALMON_LARGE, (Object)texturedModelData56.transform(SalmonEntityModel.LARGE_TRANSFORMER));
        builder.put((Object)EntityModelLayers.SHEEP, (Object)texturedModelData41);
        builder.put((Object)EntityModelLayers.SHEEP_BABY, (Object)texturedModelData41.transform(SheepEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.SHEEP_WOOL, (Object)texturedModelData42);
        builder.put((Object)EntityModelLayers.SHEEP_BABY_WOOL, (Object)texturedModelData42.transform(SheepEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.SHEEP_WOOL_UNDERCOAT, (Object)texturedModelData41);
        builder.put((Object)EntityModelLayers.SHEEP_BABY_WOOL_UNDERCOAT, (Object)texturedModelData41.transform(SheepEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.SHIELD, (Object)ShieldEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.SHULKER, (Object)ShulkerEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.SHULKER_BOX, (Object)ShulkerEntityModel.getShulkerBoxTexturedModelData());
        builder.put((Object)EntityModelLayers.SHULKER_BULLET, (Object)ShulkerBulletEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.SILVERFISH, (Object)SilverfishEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.SKELETON, (Object)texturedModelData30);
        builder.put((Object)EntityModelLayers.SKELETON_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.SKELETON_OUTER_ARMOR, (Object)texturedModelData2);
        builder.put((Object)EntityModelLayers.SKELETON_HORSE, (Object)texturedModelData7);
        builder.put((Object)EntityModelLayers.SKELETON_HORSE_BABY, (Object)texturedModelData8);
        builder.put((Object)EntityModelLayers.SKELETON_HORSE_SADDLE, (Object)texturedModelData9);
        builder.put((Object)EntityModelLayers.SKELETON_HORSE_BABY_SADDLE, (Object)texturedModelData10);
        builder.put((Object)EntityModelLayers.SKELETON_SKULL, (Object)texturedModelData6);
        builder.put((Object)EntityModelLayers.SLIME, (Object)SlimeEntityModel.getInnerTexturedModelData());
        builder.put((Object)EntityModelLayers.SLIME_OUTER, (Object)SlimeEntityModel.getOuterTexturedModelData());
        builder.put((Object)EntityModelLayers.SNIFFER, (Object)texturedModelData43);
        builder.put((Object)EntityModelLayers.SNIFFER_BABY, (Object)texturedModelData43.transform(SnifferEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.SNOW_GOLEM, (Object)SnowGolemEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.SPAWNER_MINECART, (Object)texturedModelData5);
        builder.put((Object)EntityModelLayers.SPIDER, (Object)texturedModelData32);
        builder.put((Object)EntityModelLayers.SQUID, (Object)texturedModelData54);
        builder.put((Object)EntityModelLayers.SQUID_BABY, (Object)texturedModelData54.transform(SquidEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.STRAY, (Object)texturedModelData30);
        builder.put((Object)EntityModelLayers.STRAY_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.STRAY_OUTER_ARMOR, (Object)texturedModelData2);
        builder.put((Object)EntityModelLayers.STRAY_OUTER, (Object)TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.25f), 0.0f), 64, 32));
        builder.put((Object)EntityModelLayers.STRIDER, (Object)texturedModelData27);
        builder.put((Object)EntityModelLayers.STRIDER_SADDLE, (Object)texturedModelData27);
        builder.put((Object)EntityModelLayers.STRIDER_BABY, (Object)texturedModelData27.transform(StriderEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.STRIDER_BABY_SADDLE, (Object)texturedModelData27.transform(StriderEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.TADPOLE, (Object)TadpoleEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.TNT_MINECART, (Object)texturedModelData5);
        builder.put((Object)EntityModelLayers.TRADER_LLAMA, (Object)texturedModelData25);
        builder.put((Object)EntityModelLayers.TRADER_LLAMA_BABY, (Object)texturedModelData25.transform(LlamaEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.TRIDENT, (Object)TridentEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.TROPICAL_FISH_LARGE, (Object)LargeTropicalFishEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put((Object)EntityModelLayers.TROPICAL_FISH_LARGE_PATTERN, (Object)LargeTropicalFishEntityModel.getTexturedModelData(FISH_PATTERN_DILATION));
        builder.put((Object)EntityModelLayers.TROPICAL_FISH_SMALL, (Object)SmallTropicalFishEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put((Object)EntityModelLayers.TROPICAL_FISH_SMALL_PATTERN, (Object)SmallTropicalFishEntityModel.getTexturedModelData(FISH_PATTERN_DILATION));
        builder.put((Object)EntityModelLayers.TURTLE, (Object)texturedModelData44);
        builder.put((Object)EntityModelLayers.TURTLE_BABY, (Object)texturedModelData44.transform(TurtleEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.VEX, (Object)VexEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.VILLAGER, (Object)texturedModelData31);
        builder.put((Object)EntityModelLayers.VILLAGER_BABY, (Object)texturedModelData31.transform(VillagerResemblingModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.VINDICATOR, (Object)texturedModelData11);
        builder.put((Object)EntityModelLayers.WARDEN, (Object)WardenEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.WARM_COW, (Object)texturedModelData45);
        builder.put((Object)EntityModelLayers.WARM_COW_BABY, (Object)texturedModelData45.transform(CowEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.WANDERING_TRADER, (Object)texturedModelData31);
        builder.put((Object)EntityModelLayers.WIND_CHARGE, (Object)WindChargeEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.WITCH, (Object)WitchEntityModel.getTexturedModelData().transform(modelTransformer));
        builder.put((Object)EntityModelLayers.WITHER, (Object)WitherEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put((Object)EntityModelLayers.WITHER_ARMOR, (Object)WitherEntityModel.getTexturedModelData(HAT_DILATION));
        builder.put((Object)EntityModelLayers.WITHER_SKULL, (Object)WitherSkullEntityRenderer.getTexturedModelData());
        ModelTransformer modelTransformer5 = ModelTransformer.scaling(1.2f);
        builder.put((Object)EntityModelLayers.WITHER_SKELETON, (Object)texturedModelData30.transform(modelTransformer5));
        builder.put((Object)EntityModelLayers.WITHER_SKELETON_INNER_ARMOR, (Object)texturedModelData4.transform(modelTransformer5));
        builder.put((Object)EntityModelLayers.WITHER_SKELETON_OUTER_ARMOR, (Object)texturedModelData2.transform(modelTransformer5));
        builder.put((Object)EntityModelLayers.WITHER_SKELETON_SKULL, (Object)texturedModelData6);
        builder.put((Object)EntityModelLayers.WOLF, (Object)texturedModelData46);
        builder.put((Object)EntityModelLayers.WOLF_ARMOR, (Object)texturedModelData47);
        builder.put((Object)EntityModelLayers.WOLF_BABY, (Object)texturedModelData46.transform(WolfEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.WOLF_BABY_ARMOR, (Object)texturedModelData47.transform(WolfEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOGLIN, (Object)texturedModelData28);
        builder.put((Object)EntityModelLayers.ZOGLIN_BABY, (Object)texturedModelData29);
        builder.put((Object)EntityModelLayers.ZOMBIE, (Object)texturedModelData);
        builder.put((Object)EntityModelLayers.ZOMBIE_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.ZOMBIE_OUTER_ARMOR, (Object)texturedModelData2);
        builder.put((Object)EntityModelLayers.ZOMBIE_BABY, (Object)texturedModelData.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOMBIE_BABY_INNER_ARMOR, (Object)texturedModelData4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOMBIE_BABY_OUTER_ARMOR, (Object)texturedModelData2.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOMBIE_HEAD, (Object)texturedModelData24);
        builder.put((Object)EntityModelLayers.ZOMBIE_HORSE, (Object)texturedModelData7);
        builder.put((Object)EntityModelLayers.ZOMBIE_HORSE_BABY, (Object)texturedModelData8);
        builder.put((Object)EntityModelLayers.ZOMBIE_HORSE_SADDLE, (Object)texturedModelData9);
        builder.put((Object)EntityModelLayers.ZOMBIE_HORSE_BABY_SADDLE, (Object)texturedModelData10);
        builder.put((Object)EntityModelLayers.ZOMBIE_VILLAGER, (Object)texturedModelData48);
        builder.put((Object)EntityModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, (Object)ZombieVillagerEntityModel.getArmorTexturedModelData(HAT_DILATION));
        builder.put((Object)EntityModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, (Object)ZombieVillagerEntityModel.getArmorTexturedModelData(ARMOR_DILATION));
        builder.put((Object)EntityModelLayers.ZOMBIE_VILLAGER_BABY, (Object)texturedModelData48.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOMBIE_VILLAGER_BABY_INNER_ARMOR, (Object)ZombieVillagerEntityModel.getArmorTexturedModelData(HAT_DILATION).transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOMBIE_VILLAGER_BABY_OUTER_ARMOR, (Object)ZombieVillagerEntityModel.getArmorTexturedModelData(ARMOR_DILATION).transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOMBIFIED_PIGLIN, (Object)texturedModelData22);
        builder.put((Object)EntityModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, (Object)texturedModelData4);
        builder.put((Object)EntityModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, (Object)texturedModelData3);
        builder.put((Object)EntityModelLayers.ZOMBIFIED_PIGLIN_BABY, (Object)texturedModelData22.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOMBIFIED_PIGLIN_BABY_INNER_ARMOR, (Object)texturedModelData4.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.ZOMBIFIED_PIGLIN_BABY_OUTER_ARMOR, (Object)texturedModelData3.transform(BipedEntityModel.BABY_TRANSFORMER));
        builder.put((Object)EntityModelLayers.BAMBOO_BOAT, (Object)RaftEntityModel.getTexturedModelData());
        builder.put((Object)EntityModelLayers.BAMBOO_CHEST_BOAT, (Object)RaftEntityModel.getChestTexturedModelData());
        TexturedModelData texturedModelData57 = BoatEntityModel.getTexturedModelData();
        TexturedModelData texturedModelData58 = BoatEntityModel.getChestTexturedModelData();
        builder.put((Object)EntityModelLayers.OAK_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.OAK_CHEST_BOAT, (Object)texturedModelData58);
        builder.put((Object)EntityModelLayers.SPRUCE_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.SPRUCE_CHEST_BOAT, (Object)texturedModelData58);
        builder.put((Object)EntityModelLayers.BIRCH_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.BIRCH_CHEST_BOAT, (Object)texturedModelData58);
        builder.put((Object)EntityModelLayers.JUNGLE_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.JUNGLE_CHEST_BOAT, (Object)texturedModelData58);
        builder.put((Object)EntityModelLayers.ACACIA_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.ACACIA_CHEST_BOAT, (Object)texturedModelData58);
        builder.put((Object)EntityModelLayers.CHERRY_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.CHERRY_CHEST_BOAT, (Object)texturedModelData58);
        builder.put((Object)EntityModelLayers.DARK_OAK_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.DARK_OAK_CHEST_BOAT, (Object)texturedModelData58);
        builder.put((Object)EntityModelLayers.PALE_OAK_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.PALE_OAK_CHEST_BOAT, (Object)texturedModelData58);
        builder.put((Object)EntityModelLayers.MANGROVE_BOAT, (Object)texturedModelData57);
        builder.put((Object)EntityModelLayers.MANGROVE_CHEST_BOAT, (Object)texturedModelData58);
        TexturedModelData texturedModelData59 = SignBlockEntityRenderer.getTexturedModelData(true);
        TexturedModelData texturedModelData60 = SignBlockEntityRenderer.getTexturedModelData(false);
        WoodType.stream().forEach(woodType -> {
            builder.put((Object)EntityModelLayers.createStandingSign(woodType), (Object)texturedModelData59);
            builder.put((Object)EntityModelLayers.createWallSign(woodType), (Object)texturedModelData60);
            for (HangingSignBlockEntityRenderer.AttachmentType attachmentType : HangingSignBlockEntityRenderer.AttachmentType.values()) {
                TexturedModelData texturedModelData3 = HangingSignBlockEntityRenderer.getTexturedModelData(attachmentType);
                builder.put((Object)EntityModelLayers.createHangingSign(woodType, attachmentType), (Object)texturedModelData3);
            }
        });
        ImmutableMap immutableMap = builder.build();
        List list = EntityModelLayers.getLayers().filter(layer -> !immutableMap.containsKey(layer)).collect(Collectors.toList());
        if (!list.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + String.valueOf(list));
        }
        return immutableMap;
    }
}

