/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.mojang.serialization.MapCodec
 */
package net.minecraft.registry;

import com.mojang.serialization.MapCodec;
import java.util.function.Consumer;
import net.minecraft.advancement.Advancement;
import net.minecraft.advancement.criterion.Criterion;
import net.minecraft.block.Block;
import net.minecraft.block.DecoratedPotPattern;
import net.minecraft.block.entity.BannerPattern;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.block.jukebox.JukeboxSong;
import net.minecraft.block.spawner.TrialSpawnerConfig;
import net.minecraft.command.argument.serialize.ArgumentSerializer;
import net.minecraft.component.ComponentType;
import net.minecraft.dialog.action.DialogAction;
import net.minecraft.dialog.body.DialogBody;
import net.minecraft.dialog.input.InputControl;
import net.minecraft.dialog.type.Dialog;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.enchantment.EnchantmentLevelBasedValue;
import net.minecraft.enchantment.effect.EnchantmentEntityEffect;
import net.minecraft.enchantment.effect.EnchantmentLocationBasedEffect;
import net.minecraft.enchantment.effect.EnchantmentValueEffect;
import net.minecraft.enchantment.provider.EnchantmentProvider;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.ai.brain.Activity;
import net.minecraft.entity.ai.brain.MemoryModuleType;
import net.minecraft.entity.ai.brain.Schedule;
import net.minecraft.entity.ai.brain.sensor.SensorType;
import net.minecraft.entity.attribute.EntityAttribute;
import net.minecraft.entity.damage.DamageType;
import net.minecraft.entity.decoration.painting.PaintingVariant;
import net.minecraft.entity.effect.StatusEffect;
import net.minecraft.entity.passive.CatVariant;
import net.minecraft.entity.passive.ChickenVariant;
import net.minecraft.entity.passive.CowVariant;
import net.minecraft.entity.passive.FrogVariant;
import net.minecraft.entity.passive.PigVariant;
import net.minecraft.entity.passive.WolfSoundVariant;
import net.minecraft.entity.passive.WolfVariant;
import net.minecraft.entity.spawn.SpawnCondition;
import net.minecraft.fluid.Fluid;
import net.minecraft.item.Instrument;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.consume.ConsumeEffect;
import net.minecraft.item.equipment.trim.ArmorTrimMaterial;
import net.minecraft.item.equipment.trim.ArmorTrimPattern;
import net.minecraft.item.map.MapDecorationType;
import net.minecraft.loot.LootTable;
import net.minecraft.loot.condition.LootCondition;
import net.minecraft.loot.condition.LootConditionType;
import net.minecraft.loot.entry.LootPoolEntryType;
import net.minecraft.loot.function.LootFunction;
import net.minecraft.loot.function.LootFunctionType;
import net.minecraft.loot.provider.nbt.LootNbtProviderType;
import net.minecraft.loot.provider.number.LootNumberProviderType;
import net.minecraft.loot.provider.score.LootScoreProviderType;
import net.minecraft.network.message.MessageType;
import net.minecraft.particle.ParticleType;
import net.minecraft.potion.Potion;
import net.minecraft.predicate.component.ComponentPredicate;
import net.minecraft.predicate.entity.EntitySubPredicate;
import net.minecraft.recipe.Recipe;
import net.minecraft.recipe.RecipeSerializer;
import net.minecraft.recipe.RecipeType;
import net.minecraft.recipe.book.RecipeBookCategory;
import net.minecraft.recipe.display.RecipeDisplay;
import net.minecraft.recipe.display.SlotDisplay;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.scoreboard.number.NumberFormatType;
import net.minecraft.screen.ScreenHandlerType;
import net.minecraft.server.world.ChunkTicketType;
import net.minecraft.sound.SoundEvent;
import net.minecraft.stat.StatType;
import net.minecraft.structure.StructurePieceType;
import net.minecraft.structure.StructureSet;
import net.minecraft.structure.pool.StructurePool;
import net.minecraft.structure.pool.StructurePoolElementType;
import net.minecraft.structure.pool.alias.StructurePoolAliasBinding;
import net.minecraft.structure.processor.StructureProcessorList;
import net.minecraft.structure.processor.StructureProcessorType;
import net.minecraft.structure.rule.PosRuleTestType;
import net.minecraft.structure.rule.RuleTestType;
import net.minecraft.structure.rule.blockentity.RuleBlockEntityModifierType;
import net.minecraft.test.TestContext;
import net.minecraft.test.TestEnvironmentDefinition;
import net.minecraft.test.TestInstance;
import net.minecraft.util.Identifier;
import net.minecraft.util.math.floatprovider.FloatProviderType;
import net.minecraft.util.math.intprovider.IntProviderType;
import net.minecraft.util.math.noise.DoublePerlinNoiseSampler;
import net.minecraft.village.VillagerProfession;
import net.minecraft.village.VillagerType;
import net.minecraft.world.World;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.source.BiomeSource;
import net.minecraft.world.biome.source.MultiNoiseBiomeSourceParameterList;
import net.minecraft.world.chunk.ChunkStatus;
import net.minecraft.world.dimension.DimensionOptions;
import net.minecraft.world.dimension.DimensionType;
import net.minecraft.world.event.GameEvent;
import net.minecraft.world.event.PositionSourceType;
import net.minecraft.world.gen.FlatLevelGeneratorPreset;
import net.minecraft.world.gen.WorldPreset;
import net.minecraft.world.gen.blockpredicate.BlockPredicateType;
import net.minecraft.world.gen.carver.Carver;
import net.minecraft.world.gen.carver.ConfiguredCarver;
import net.minecraft.world.gen.chunk.ChunkGenerator;
import net.minecraft.world.gen.chunk.ChunkGeneratorSettings;
import net.minecraft.world.gen.chunk.placement.StructurePlacementType;
import net.minecraft.world.gen.densityfunction.DensityFunction;
import net.minecraft.world.gen.feature.ConfiguredFeature;
import net.minecraft.world.gen.feature.Feature;
import net.minecraft.world.gen.feature.PlacedFeature;
import net.minecraft.world.gen.feature.size.FeatureSizeType;
import net.minecraft.world.gen.foliage.FoliagePlacerType;
import net.minecraft.world.gen.heightprovider.HeightProviderType;
import net.minecraft.world.gen.placementmodifier.PlacementModifierType;
import net.minecraft.world.gen.root.RootPlacerType;
import net.minecraft.world.gen.stateprovider.BlockStateProviderType;
import net.minecraft.world.gen.structure.Structure;
import net.minecraft.world.gen.structure.StructureType;
import net.minecraft.world.gen.surfacebuilder.MaterialRules;
import net.minecraft.world.gen.treedecorator.TreeDecoratorType;
import net.minecraft.world.gen.trunk.TrunkPlacerType;
import net.minecraft.world.poi.PointOfInterestType;

public class RegistryKeys {
    final static public Identifier ROOT = Identifier.ofVanilla("root");
    final static public RegistryKey<Registry<Activity>> ACTIVITY = RegistryKeys.of("activity");
    final static public RegistryKey<Registry<EntityAttribute>> ATTRIBUTE = RegistryKeys.of("attribute");
    final static public RegistryKey<Registry<MapCodec<? extends BiomeSource>>> BIOME_SOURCE = RegistryKeys.of("worldgen/biome_source");
    final static public RegistryKey<Registry<BlockEntityType<?>>> BLOCK_ENTITY_TYPE = RegistryKeys.of("block_entity_type");
    final static public RegistryKey<Registry<BlockPredicateType<?>>> BLOCK_PREDICATE_TYPE = RegistryKeys.of("block_predicate_type");
    final static public RegistryKey<Registry<BlockStateProviderType<?>>> BLOCK_STATE_PROVIDER_TYPE = RegistryKeys.of("worldgen/block_state_provider_type");
    final static public RegistryKey<Registry<MapCodec<? extends Block>>> BLOCK_TYPE = RegistryKeys.of("block_type");
    final static public RegistryKey<Registry<Block>> BLOCK = RegistryKeys.of("block");
    final static public RegistryKey<Registry<Carver<?>>> CARVER = RegistryKeys.of("worldgen/carver");
    final static public RegistryKey<Registry<MapCodec<? extends ChunkGenerator>>> CHUNK_GENERATOR = RegistryKeys.of("worldgen/chunk_generator");
    final static public RegistryKey<Registry<ChunkStatus>> CHUNK_STATUS = RegistryKeys.of("chunk_status");
    final static public RegistryKey<Registry<ArgumentSerializer<?, ?>>> COMMAND_ARGUMENT_TYPE = RegistryKeys.of("command_argument_type");
    final static public RegistryKey<Registry<ConsumeEffect.Type<?>>> CONSUME_EFFECT_TYPE = RegistryKeys.of("consume_effect_type");
    final static public RegistryKey<Registry<ItemGroup>> ITEM_GROUP = RegistryKeys.of("creative_mode_tab");
    final static public RegistryKey<Registry<Identifier>> CUSTOM_STAT = RegistryKeys.of("custom_stat");
    final static public RegistryKey<Registry<ComponentPredicate.Type<?>>> DATA_COMPONENT_PREDICATE_TYPE = RegistryKeys.of("data_component_predicate_type");
    final static public RegistryKey<Registry<ComponentType<?>>> DATA_COMPONENT_TYPE = RegistryKeys.of("data_component_type");
    final static public RegistryKey<Registry<DecoratedPotPattern>> DECORATED_POT_PATTERN = RegistryKeys.of("decorated_pot_pattern");
    final static public RegistryKey<Registry<MapCodec<? extends DensityFunction>>> DENSITY_FUNCTION_TYPE = RegistryKeys.of("worldgen/density_function_type");
    final static public RegistryKey<Registry<MapCodec<? extends DialogBody>>> DIALOG_BODY_TYPE = RegistryKeys.of("dialog_body_type");
    final static public RegistryKey<Registry<MapCodec<? extends Dialog>>> DIALOG_TYPE = RegistryKeys.of("dialog_type");
    final static public RegistryKey<Registry<ComponentType<?>>> ENCHANTMENT_EFFECT_COMPONENT_TYPE = RegistryKeys.of("enchantment_effect_component_type");
    final static public RegistryKey<Registry<MapCodec<? extends EnchantmentEntityEffect>>> ENCHANTMENT_ENTITY_EFFECT_TYPE = RegistryKeys.of("enchantment_entity_effect_type");
    final static public RegistryKey<Registry<MapCodec<? extends EnchantmentLevelBasedValue>>> ENCHANTMENT_LEVEL_BASED_VALUE_TYPE = RegistryKeys.of("enchantment_level_based_value_type");
    final static public RegistryKey<Registry<MapCodec<? extends EnchantmentLocationBasedEffect>>> ENCHANTMENT_LOCATION_BASED_EFFECT_TYPE = RegistryKeys.of("enchantment_location_based_effect_type");
    final static public RegistryKey<Registry<MapCodec<? extends EnchantmentProvider>>> ENCHANTMENT_PROVIDER_TYPE = RegistryKeys.of("enchantment_provider_type");
    final static public RegistryKey<Registry<MapCodec<? extends EnchantmentValueEffect>>> ENCHANTMENT_VALUE_EFFECT_TYPE = RegistryKeys.of("enchantment_value_effect_type");
    final static public RegistryKey<Registry<MapCodec<? extends EntitySubPredicate>>> ENTITY_SUB_PREDICATE_TYPE = RegistryKeys.of("entity_sub_predicate_type");
    final static public RegistryKey<Registry<EntityType<?>>> ENTITY_TYPE = RegistryKeys.of("entity_type");
    final static public RegistryKey<Registry<FeatureSizeType<?>>> FEATURE_SIZE_TYPE = RegistryKeys.of("worldgen/feature_size_type");
    final static public RegistryKey<Registry<Feature<?>>> FEATURE = RegistryKeys.of("worldgen/feature");
    final static public RegistryKey<Registry<FloatProviderType<?>>> FLOAT_PROVIDER_TYPE = RegistryKeys.of("float_provider_type");
    final static public RegistryKey<Registry<Fluid>> FLUID = RegistryKeys.of("fluid");
    final static public RegistryKey<Registry<FoliagePlacerType<?>>> FOLIAGE_PLACER_TYPE = RegistryKeys.of("worldgen/foliage_placer_type");
    final static public RegistryKey<Registry<GameEvent>> GAME_EVENT = RegistryKeys.of("game_event");
    final static public RegistryKey<Registry<HeightProviderType<?>>> HEIGHT_PROVIDER_TYPE = RegistryKeys.of("height_provider_type");
    final static public RegistryKey<Registry<MapCodec<? extends InputControl>>> INPUT_CONTROL_TYPE = RegistryKeys.of("input_control_type");
    final static public RegistryKey<Registry<IntProviderType<?>>> INT_PROVIDER_TYPE = RegistryKeys.of("int_provider_type");
    final static public RegistryKey<Registry<Item>> ITEM = RegistryKeys.of("item");
    final static public RegistryKey<Registry<LootConditionType>> LOOT_CONDITION_TYPE = RegistryKeys.of("loot_condition_type");
    final static public RegistryKey<Registry<LootFunctionType<?>>> LOOT_FUNCTION_TYPE = RegistryKeys.of("loot_function_type");
    final static public RegistryKey<Registry<LootNbtProviderType>> LOOT_NBT_PROVIDER_TYPE = RegistryKeys.of("loot_nbt_provider_type");
    final static public RegistryKey<Registry<LootNumberProviderType>> LOOT_NUMBER_PROVIDER_TYPE = RegistryKeys.of("loot_number_provider_type");
    final static public RegistryKey<Registry<LootPoolEntryType>> LOOT_POOL_ENTRY_TYPE = RegistryKeys.of("loot_pool_entry_type");
    final static public RegistryKey<Registry<LootScoreProviderType>> LOOT_SCORE_PROVIDER_TYPE = RegistryKeys.of("loot_score_provider_type");
    final static public RegistryKey<Registry<MapDecorationType>> MAP_DECORATION_TYPE = RegistryKeys.of("map_decoration_type");
    final static public RegistryKey<Registry<MapCodec<? extends MaterialRules.MaterialCondition>>> MATERIAL_CONDITION = RegistryKeys.of("worldgen/material_condition");
    final static public RegistryKey<Registry<MapCodec<? extends MaterialRules.MaterialRule>>> MATERIAL_RULE = RegistryKeys.of("worldgen/material_rule");
    final static public RegistryKey<Registry<MemoryModuleType<?>>> MEMORY_MODULE_TYPE = RegistryKeys.of("memory_module_type");
    final static public RegistryKey<Registry<ScreenHandlerType<?>>> SCREEN_HANDLER = RegistryKeys.of("menu");
    final static public RegistryKey<Registry<StatusEffect>> STATUS_EFFECT = RegistryKeys.of("mob_effect");
    final static public RegistryKey<Registry<NumberFormatType<?>>> NUMBER_FORMAT_TYPE = RegistryKeys.of("number_format_type");
    final static public RegistryKey<Registry<ParticleType<?>>> PARTICLE_TYPE = RegistryKeys.of("particle_type");
    final static public RegistryKey<Registry<PlacementModifierType<?>>> PLACEMENT_MODIFIER_TYPE = RegistryKeys.of("worldgen/placement_modifier_type");
    final static public RegistryKey<Registry<PointOfInterestType>> POINT_OF_INTEREST_TYPE = RegistryKeys.of("point_of_interest_type");
    final static public RegistryKey<Registry<MapCodec<? extends StructurePoolAliasBinding>>> POOL_ALIAS_BINDING = RegistryKeys.of("worldgen/pool_alias_binding");
    final static public RegistryKey<Registry<PositionSourceType<?>>> POSITION_SOURCE_TYPE = RegistryKeys.of("position_source_type");
    final static public RegistryKey<Registry<PosRuleTestType<?>>> POS_RULE_TEST = RegistryKeys.of("pos_rule_test");
    final static public RegistryKey<Registry<Potion>> POTION = RegistryKeys.of("potion");
    final static public RegistryKey<Registry<RecipeBookCategory>> RECIPE_BOOK_CATEGORY = RegistryKeys.of("recipe_book_category");
    final static public RegistryKey<Registry<RecipeDisplay.Serializer<?>>> RECIPE_DISPLAY = RegistryKeys.of("recipe_display");
    final static public RegistryKey<Registry<RecipeSerializer<?>>> RECIPE_SERIALIZER = RegistryKeys.of("recipe_serializer");
    final static public RegistryKey<Registry<RecipeType<?>>> RECIPE_TYPE = RegistryKeys.of("recipe_type");
    final static public RegistryKey<Registry<RootPlacerType<?>>> ROOT_PLACER_TYPE = RegistryKeys.of("worldgen/root_placer_type");
    final static public RegistryKey<Registry<RuleBlockEntityModifierType<?>>> RULE_BLOCK_ENTITY_MODIFIER = RegistryKeys.of("rule_block_entity_modifier");
    final static public RegistryKey<Registry<RuleTestType<?>>> RULE_TEST = RegistryKeys.of("rule_test");
    final static public RegistryKey<Registry<Schedule>> SCHEDULE = RegistryKeys.of("schedule");
    final static public RegistryKey<Registry<SensorType<?>>> SENSOR_TYPE = RegistryKeys.of("sensor_type");
    final static public RegistryKey<Registry<SlotDisplay.Serializer<?>>> SLOT_DISPLAY = RegistryKeys.of("slot_display");
    final static public RegistryKey<Registry<SoundEvent>> SOUND_EVENT = RegistryKeys.of("sound_event");
    final static public RegistryKey<Registry<MapCodec<? extends SpawnCondition>>> SPAWN_CONDITION_TYPE = RegistryKeys.of("spawn_condition_type");
    final static public RegistryKey<Registry<StatType<?>>> STAT_TYPE = RegistryKeys.of("stat_type");
    final static public RegistryKey<Registry<StructurePieceType>> STRUCTURE_PIECE = RegistryKeys.of("worldgen/structure_piece");
    final static public RegistryKey<Registry<StructurePlacementType<?>>> STRUCTURE_PLACEMENT = RegistryKeys.of("worldgen/structure_placement");
    final static public RegistryKey<Registry<StructurePoolElementType<?>>> STRUCTURE_POOL_ELEMENT = RegistryKeys.of("worldgen/structure_pool_element");
    final static public RegistryKey<Registry<StructureProcessorType<?>>> STRUCTURE_PROCESSOR = RegistryKeys.of("worldgen/structure_processor");
    final static public RegistryKey<Registry<StructureType<?>>> STRUCTURE_TYPE = RegistryKeys.of("worldgen/structure_type");
    final static public RegistryKey<Registry<MapCodec<? extends DialogAction>>> DIALOG_ACTION_TYPE = RegistryKeys.of("dialog_action_type");
    final static public RegistryKey<Registry<MapCodec<? extends TestEnvironmentDefinition>>> TEST_ENVIRONMENT_DEFINITION_TYPE = RegistryKeys.of("test_environment_definition_type");
    final static public RegistryKey<Registry<Consumer<TestContext>>> TEST_FUNCTION = RegistryKeys.of("test_function");
    final static public RegistryKey<Registry<MapCodec<? extends TestInstance>>> TEST_INSTANCE_TYPE = RegistryKeys.of("test_instance_type");
    final static public RegistryKey<Registry<ChunkTicketType>> TICKET_TYPE = RegistryKeys.of("ticket_type");
    final static public RegistryKey<Registry<TreeDecoratorType<?>>> TREE_DECORATOR_TYPE = RegistryKeys.of("worldgen/tree_decorator_type");
    final static public RegistryKey<Registry<TrunkPlacerType<?>>> TRUNK_PLACER_TYPE = RegistryKeys.of("worldgen/trunk_placer_type");
    final static public RegistryKey<Registry<VillagerProfession>> VILLAGER_PROFESSION = RegistryKeys.of("villager_profession");
    final static public RegistryKey<Registry<VillagerType>> VILLAGER_TYPE = RegistryKeys.of("villager_type");
    final static public RegistryKey<Registry<BannerPattern>> BANNER_PATTERN = RegistryKeys.of("banner_pattern");
    final static public RegistryKey<Registry<Biome>> BIOME = RegistryKeys.of("worldgen/biome");
    final static public RegistryKey<Registry<CatVariant>> CAT_VARIANT = RegistryKeys.of("cat_variant");
    final static public RegistryKey<Registry<MessageType>> MESSAGE_TYPE = RegistryKeys.of("chat_type");
    final static public RegistryKey<Registry<ChickenVariant>> CHICKEN_VARIANT = RegistryKeys.of("chicken_variant");
    final static public RegistryKey<Registry<ConfiguredCarver<?>>> CONFIGURED_CARVER = RegistryKeys.of("worldgen/configured_carver");
    final static public RegistryKey<Registry<ConfiguredFeature<?, ?>>> CONFIGURED_FEATURE = RegistryKeys.of("worldgen/configured_feature");
    final static public RegistryKey<Registry<CowVariant>> COW_VARIANT = RegistryKeys.of("cow_variant");
    final static public RegistryKey<Registry<DamageType>> DAMAGE_TYPE = RegistryKeys.of("damage_type");
    final static public RegistryKey<Registry<DensityFunction>> DENSITY_FUNCTION = RegistryKeys.of("worldgen/density_function");
    final static public RegistryKey<Registry<Dialog>> DIALOG = RegistryKeys.of("dialog");
    final static public RegistryKey<Registry<DimensionType>> DIMENSION_TYPE = RegistryKeys.of("dimension_type");
    final static public RegistryKey<Registry<EnchantmentProvider>> ENCHANTMENT_PROVIDER = RegistryKeys.of("enchantment_provider");
    final static public RegistryKey<Registry<Enchantment>> ENCHANTMENT = RegistryKeys.of("enchantment");
    final static public RegistryKey<Registry<FlatLevelGeneratorPreset>> FLAT_LEVEL_GENERATOR_PRESET = RegistryKeys.of("worldgen/flat_level_generator_preset");
    final static public RegistryKey<Registry<FrogVariant>> FROG_VARIANT = RegistryKeys.of("frog_variant");
    final static public RegistryKey<Registry<Instrument>> INSTRUMENT = RegistryKeys.of("instrument");
    final static public RegistryKey<Registry<JukeboxSong>> JUKEBOX_SONG = RegistryKeys.of("jukebox_song");
    final static public RegistryKey<Registry<MultiNoiseBiomeSourceParameterList>> MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST = RegistryKeys.of("worldgen/multi_noise_biome_source_parameter_list");
    final static public RegistryKey<Registry<ChunkGeneratorSettings>> CHUNK_GENERATOR_SETTINGS = RegistryKeys.of("worldgen/noise_settings");
    final static public RegistryKey<Registry<DoublePerlinNoiseSampler.NoiseParameters>> NOISE_PARAMETERS = RegistryKeys.of("worldgen/noise");
    final static public RegistryKey<Registry<PaintingVariant>> PAINTING_VARIANT = RegistryKeys.of("painting_variant");
    final static public RegistryKey<Registry<PigVariant>> PIG_VARIANT = RegistryKeys.of("pig_variant");
    final static public RegistryKey<Registry<PlacedFeature>> PLACED_FEATURE = RegistryKeys.of("worldgen/placed_feature");
    final static public RegistryKey<Registry<StructureProcessorList>> PROCESSOR_LIST = RegistryKeys.of("worldgen/processor_list");
    final static public RegistryKey<Registry<StructureSet>> STRUCTURE_SET = RegistryKeys.of("worldgen/structure_set");
    final static public RegistryKey<Registry<Structure>> STRUCTURE = RegistryKeys.of("worldgen/structure");
    final static public RegistryKey<Registry<StructurePool>> TEMPLATE_POOL = RegistryKeys.of("worldgen/template_pool");
    final static public RegistryKey<Registry<TestEnvironmentDefinition>> TEST_ENVIRONMENT = RegistryKeys.of("test_environment");
    final static public RegistryKey<Registry<TestInstance>> TEST_INSTANCE = RegistryKeys.of("test_instance");
    final static public RegistryKey<Registry<TrialSpawnerConfig>> TRIAL_SPAWNER = RegistryKeys.of("trial_spawner");
    final static public RegistryKey<Registry<Criterion<?>>> CRITERION = RegistryKeys.of("trigger_type");
    final static public RegistryKey<Registry<ArmorTrimMaterial>> TRIM_MATERIAL = RegistryKeys.of("trim_material");
    final static public RegistryKey<Registry<ArmorTrimPattern>> TRIM_PATTERN = RegistryKeys.of("trim_pattern");
    final static public RegistryKey<Registry<WolfVariant>> WOLF_VARIANT = RegistryKeys.of("wolf_variant");
    final static public RegistryKey<Registry<WolfSoundVariant>> WOLF_SOUND_VARIANT = RegistryKeys.of("wolf_sound_variant");
    final static public RegistryKey<Registry<WorldPreset>> WORLD_PRESET = RegistryKeys.of("worldgen/world_preset");
    final static public RegistryKey<Registry<World>> WORLD = RegistryKeys.of("dimension");
    final static public RegistryKey<Registry<DimensionOptions>> DIMENSION = RegistryKeys.of("dimension");
    final static public RegistryKey<Registry<LootTable>> LOOT_TABLE = RegistryKeys.of("loot_table");
    final static public RegistryKey<Registry<LootFunction>> ITEM_MODIFIER = RegistryKeys.of("item_modifier");
    final static public RegistryKey<Registry<LootCondition>> PREDICATE = RegistryKeys.of("predicate");
    final static public RegistryKey<Registry<Advancement>> ADVANCEMENT = RegistryKeys.of("advancement");
    final static public RegistryKey<Registry<Recipe<?>>> RECIPE = RegistryKeys.of("recipe");

    public static RegistryKey<World> toWorldKey(RegistryKey<DimensionOptions> key) {
        return RegistryKey.of(WORLD, key.getValue());
    }

    public static RegistryKey<DimensionOptions> toDimensionKey(RegistryKey<World> key) {
        return RegistryKey.of(DIMENSION, key.getValue());
    }

    private static <T> RegistryKey<Registry<T>> of(String id) {
        return RegistryKey.ofRegistry(Identifier.ofVanilla(id));
    }

    public static String getPath(RegistryKey<? extends Registry<?>> registryRef) {
        return registryRef.getValue().getPath();
    }

    public static String getTagPath(RegistryKey<? extends Registry<?>> registryRef) {
        return "tags/" + registryRef.getValue().getPath();
    }
}

